<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.trade</groupId>
        <artifactId>trade-manager</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>trade-manager-trade</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Trade Manager - Trade</name>
    <description>Trade Manager components</description>
    <properties>
        <org.codehaus.mojo.version>3.6.3</org.codehaus.mojo.version>
        <org.jfree.jfreechart.version>1.5.5</org.jfree.jfreechart.version>
        <de.sciss.syntaxpane.version>1.3.0</de.sciss.syntaxpane.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>${org.jfree.jfreechart.version}</version>
        </dependency>
        <dependency>
            <groupId>de.sciss</groupId>
            <artifactId>syntaxpane</artifactId>
            <version>${de.sciss.syntaxpane.version}</version>
        </dependency>
        <dependency>
            <groupId>org.trade</groupId>
            <artifactId>trade-manager-core</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.trade</groupId>
            <artifactId>trade-manager-core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${org.codehaus.mojo.version}</version>
                <configuration>
                    <mainClass>org.trade.ui.TradeAppMain</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <mainClass>org.trade.ui.TradeApplication</mainClass>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <systemPropertyVariables>
                        <user.timezone>America/New_York</user.timezone>
                        <trade.config>file:../config.properties</trade.config>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>