package org.trade.core.persistent.strategy.series.indicator.rsi;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public class RelativeStrengthIndex implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7644763985378994305L;

    private BigDecimal relativeStrengthIndex;

    public RelativeStrengthIndex() {
    }

    /**
     * Constructor for RelativeStrengthIndex.
     *
     * @param relativeStrengthIndex BigDecimal
     */
    public RelativeStrengthIndex(BigDecimal relativeStrengthIndex) {
        this.relativeStrengthIndex = relativeStrengthIndex;
    }

    /**
     * Method getRelativeStrengthIndex.
     *
     * @return BigDecimal
     */
    public BigDecimal getRelativeStrengthIndex() {
        return this.relativeStrengthIndex;
    }

    /**
     * Method setRelativeStrengthIndex.
     *
     * @param relativeStrengthIndex BigDecimal
     */
    public void setRelativeStrengthIndex(BigDecimal relativeStrengthIndex) {
        this.relativeStrengthIndex = relativeStrengthIndex;
    }
}
