language: java
jdk:
- openjdk23
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: 126ELo8iNKUg7K2a3c27cfEN3tPluL3YuSe2I4GqViBIQKIlSSlVK/3OPQhWRk13OP/BuNB6QK/8/5QbRuWS4Bwbf3bvfLJBcpLpRprDLmejt99Gxsee6mDOHrhdnXstJkGrVdTY0O/Hwu5WxIh8T1oVbGM7H0dH1Vtnw92j5CiItR4gXyVLDwtYL9pbmRdYTLjTnSlwo+eAKH/fH2DUIq3IJ1ThidvFbb5ghe7cYQEfNr77CZpeg2ztXC3xGF3asJ+lTSdyPyZ3QJPVDOagfqwWmrjK7bnxw76VSIvP0wr9rofdijwEwgWaRY4KeUX+CNEGtpoRaDb4NzIbTZCo1ctz6hJue+Hc2nR9cchCgnDnWB7CGZwER0YvIbCJ8SMskC4sLAU1QXw6KKRP5jXH9O1BnCiZdHDFoqLgrm5w4bNNA2+2sP5mGbzpexGdyGyKOxbJKi1ZO5ogmAkz+uxwKtTdyyg9yl/w6eMYjxcYdsC4+OXuP/WCH0CrXqBJeEMaBt+RVOinVXSzwVl3tFOc5lLIbEJCRhjEWn3GYQoUkccxUySpZiIaIOqAwEyD67AsA/sGR9LNQTcgijRNkQiLK9srI09mcPE1X3JG1vrYjZXy+Ko1iXALpSsNmxcNf+24E22sVOEC+bT1+z5O6OBTXjtdfg4zRWB7XvMiHvSZUyE=
