---
tags: [trade]
projects: [spring-data-rest,spring-data-jpa,spring-hateoas,spring-security,spring-boot,]
---
:toc: left
:icons: font
:source-highlighter: prettify
:image-width: 500

= Trade Manager

Environment

Maven 3.2 or higher 
Git  
MySQL 5.6.24  
Java 1.8.x recommend latest version
IntelliJ open source version  


1/ To clone from command line  

$git clone <URL> i.e. https://github.com/trade-manager/trade-manager-web.git 

2/ Install the DB from the script i.e run the scripts in web/src/main/resources/schema as root. 

schema-mysql.sql create schema tradeprod.
drop-create-user-mysql.sql creates the DB user trader fpr tradeprod.
data-mysql.sql adds defaults data.

3/ Add the tools-1.8.0.jar to the .m2 repo. From the project dir 

$mvn install:install-file -Dfile=web/lib/tools-1.8.0.jar -DgroupId=com.sun -DartifactId=tools -Dversion=1.8.0 -Dpackaging=jar

8/ Build the project from the project dir 

$mvn clean install (make sure $JAVA_HOME is version 1.8)

9/ Open IntelliJ and import the parent pom.xml from the project dir. 

10/ Add the Maven Wrapper. From project dir run  

$mvn -N io.takari:maven:wrapper  

10/ To run the old Swing UI. From project dir, cd web, then run

$mvnw -Duser.timezone=America/New_York -Dlog4j.configuration=file:config.properties exec:java  

include::core/README.adoc[leveloffset=+1]
include::trade/README.adoc[leveloffset=+1]
include::strategies/README.adoc[leveloffset=+1]
include::web/README.adoc[leveloffset=+1]
