---
tags: [trade]
projects: [spring-data-rest,spring-data-jpa,spring-hateoas,spring-security,spring-boot,]
---
:toc: left
:icons: font
:source-highlighter: prettify
:image-width: 500

= Trade Manager

Environment

Maven 3.9 or higher,
Git,  
mariadb 11.7.2 or higher,
Java 23.x recommend latest version,
IntelliJ open source version  

1/ To clone the repo from the command line  

$git clone <URL> i.e. https://github.com/trade-manager/trade-manager-web.git

2/ Change the following properties in the project dir db.properties file: db-dba.username(root is default)/db-dba.password. Note the db-dba.username must have schema create privileges i.e. root. The other values can be changed if so desired.

3/ Create the mariadb DB. From project dir, cd web, then run (make sure $JAVA_HOME is version 1.8, check with $>echo $JAVA_HOME).

>$mvn clean install

>$ cd web

web>$mvnw initialize sql:execute

Note demo data for 2024 is not added by default uncomment the file in the web/pom.xml if not needed.

4/ To run the old Swing UI. From project dir, cd web, then run

web>$mvnw -Dtrade.config=file:../config.properties exec:java

OR the new Spring boot Web app

web>$mvnw spring-boot:run   Note WIP so not much to see yet

5/ Open IntelliJ and import the parent pom.xml from the project dir. You can now set run configurations for 6/

In IntelliJ, Edit Configuration add a Maven set working dir to /web then set command line to above without mvnw.

If you wish to deploy the app to another director after building it complete the following:

6/ Copy config.properties, web/target/trade-manager-web-0.0.1-SNAPSHOT.jar, strategies dir and web/pom.xml to your new directory.

    b/ Change the following config.properties values to trade.csv.default.dir=temp and trade.strategy.default.dir=strategies

    c/ To run the old Swing UI from the command line"

>$mvn exec:java -Dexec.mainClass="org.trade.ui.TradeAppMain" -Dexec.args="-Dtrade.config=config.properties"
