---
tags: [trade]
projects: [spring-data-rest,spring-data-jpa,spring-hateoas,spring-security,spring-boot,]
---
:toc: left
:icons: font
:source-highlighter: prettify
:image-width: 500

= Trade Manager

Environment

Maven 3.2 or higher, 
Git,  
MySQL 5.6.24,   
Java 1.8.x recommend latest version, 
IntelliJ open source version  


1/ To clone from command line  

$git clone <URL> i.e. https://github.com/trade-manager/trade-manager-web.git

2/ Change the following properties in the project dir db.properties file db-dba.user/db-dba.password/db-user.user/db-user.password set these to a user who can create schemas and users (root will do).

3/ Add the tools-1.8.0.jar to the .m2 repo. From the project dir 

$mvn install:install-file -Dfile=lib/tools-1.8.0.jar -DgroupId=com.sun -DartifactId=tools -Dversion=1.8.0 -Dpackaging=jar

4/ Add the Maven Wrapper. From project dir run  

$mvn -N io.takari:maven:wrapper

5/ Build the project from the project dir 

$mvn clean install (make sure $JAVA_HOME is version 1.8)

6/ Open IntelliJ and import the parent pom.xml from the project dir. 

6/ Create the MySQL DB. From project dir, cd web, then run

$ mvnw initialize sql:execute

7/ To run the old Swing UI. From project dir, cd web, then run

$mvnw -Duser.timezone=America/New_York -Dlog4j.configuration=file:../config.properties exec:java  

OR the new Spring boot Web app

$mvnw spring-boot:run   Note WIP so not much to see yet

In IntelliJ, Edit Configuration add a Maven set working dir to /web then set command line to above without mvnw.
