---
tags: [trade]
projects: [spring-data-rest,spring-data-jpa,spring-hateoas,spring-security,spring-boot,]
---
:toc: left
:icons: font
:source-highlighter: prettify
:image-width: 500

= Trade Manager

Environment

Maven 3.2 or higher, 
Git,  
MySQL 5.6.24,   
Java 1.8.x recommend latest version, 
IntelliJ open source version  


1/ To clone from command line  

$git clone <URL> i.e. https://github.com/trade-manager/trade-manager-web.git 

2/ Add the tools-1.8.0.jar to the .m2 repo. From the project dir 

$mvn install:install-file -Dfile=lib/tools-1.8.0.jar -DgroupId=com.sun -DartifactId=tools -Dversion=1.8.0 -Dpackaging=jar

3/ Build the project from the project dir 

$mvn clean install (make sure $JAVA_HOME is version 1.8)

4/ Open IntelliJ and import the parent pom.xml from the project dir. 

5/ Add the Maven Wrapper. From project dir run  

$mvn -N io.takari:maven:wrapper  

6/ Install the DB from the script i.e run the scripts in /db as root. Note uncomment the DELIMITER statement. The scripts can also be run by following the instructions in the project /web resources/application.properties

db/schema-mysql.sql - create schema tradeprod.
db/drop-create-user-mysql.sql - creates the DB user trader fpr tradeprod.
db/data-mysql.sql - adds defaults data.

7/ To run the old Swing UI. From project dir, cd web, then run

$mvnw -Duser.timezone=America/New_York -Dlog4j.configuration=file:../config.properties exec:java  

OR the new Spring boot Web app

$mvnw spring-boot:run   Note WIP so not much to see yet

In IntelliJ, Edit Configuration add a Maven set working dir to /web then set command line to above without mvnw.
