package org.trade.core.util;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.aspect.Aspect;

import java.io.Serial;
import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Random;


/**
 * Contract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class Log extends Aspect implements Serializable, Cloneable {


    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 5691902477608387034L;

    private ZonedDateTime timestamp;
    private String level;
    private String thread;
    String logger;
    private String message;

    public Log() {
    }

    /**
     * Constructor for Contract.
     *
     * @param timestamp String
     * @param level     String
     * @param thread    String
     * @param logger    String
     * @param message   Date
     */
    public Log(ZonedDateTime timestamp,
               String level,
               String thread,
               String logger,
               String message) {

        this.timestamp = timestamp;
        this.level = level;
        this.thread = thread;
        this.logger = logger;
        this.message = message;
    }

    /**
     * Method getTimestamp.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Method setTimestamp.
     *
     * @param timestamp ZonedDateTime
     */
    public void setTimestamp(ZonedDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Method getLevel.
     *
     * @return String
     */
    public String getLevel() {
        return this.level;
    }

    /**
     * Method setLevel.
     *
     * @param level String
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * Method getThread.
     *
     * @return String
     */
    public String getThread() {
        return this.thread;
    }

    /**
     * Method setThread.
     *
     * @param thread String
     */
    public void setThread(String thread) {
        this.thread = thread;
    }

    /**
     * Method getLogger.
     *
     * @return String
     */
    public String getLogger() {
        return this.logger;
    }

    /**
     * Method setLogger.
     *
     * @param logger String
     */
    public void setLogger(String logger) {
        this.logger = logger;
    }

    /**
     * Method getMessage.
     *
     * @return String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Method setMessage.
     *
     * @param message String
     */
    public void setMessage(String message) {
        this.message = message;
    }


    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        return super.clone();
    }

    /**
     * Method hashCode.
     * <p>
     * For every field tested in the equals-Method, calculate a hash code c by:
     * <p>
     * If the field f is a boolean: calculate * (f ? 0 : 1);
     * <p>
     * If the field f is a byte, char, short or int: calculate (int)f;
     * <p>
     * If the field f is a long: calculate (int)(f ^ (f >>> 32));
     * <p>
     * If the field f is a float: calculate Float.floatToIntBits(f);
     * <p>
     * If the field f is a double: calculate Double.doubleToLongBits(f) and
     * handle the return value like every long value;
     * <p>
     * If the field f is an object: Use the result of the hashCode() method or 0
     * if f == null;
     * <p>
     * If the field f is an array: See every field as separate element and
     * calculate the hash value in a recursive fashion and combine the values as
     * described next.
     *
     * @return int
     */
    public int hashCode() {

        int hash = super.hashCode();
        hash = hash + this.getLevel().hashCode();
        hash = hash + this.getLogger().hashCode();
        hash = hash + this.getThread().hashCode();
        hash = hash + this.getMessage().hashCode();
        hash = hash + this.getTimestamp().hashCode();
        return hash;
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return this.getMessage();
    }
}
