package org.trade.core.persistent.strategy.series.indicator.pivot;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public class Pivot implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7644763985378994305L;

    private BigDecimal pivotPrice;
    private String pivotSide;

    public Pivot() {
    }

    /**
     * Constructor for Pivot.
     *
     * @param pivotPrice BigDecimal
     * @param pivotSide  String
     */
    public Pivot(BigDecimal pivotPrice, String pivotSide) {
        this.pivotPrice = pivotPrice;
        this.pivotSide = pivotSide;
    }

    /**
     * Method getPivotPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getPivotPrice() {
        return this.pivotPrice;
    }

    /**
     * Method setPivotPrice.
     *
     * @param pivotPrice BigDecimal
     */
    public void setPivotPrice(BigDecimal pivotPrice) {
        this.pivotPrice = pivotPrice;
    }

    /**
     * Method getPivotSide.
     *
     * @return String
     */
    public String getPivotSide() {
        return this.pivotSide;
    }

    /**
     * Method setPivotSide.
     *
     * @param pivotSide String
     */
    public void setPivotSide(String pivotSide) {
        this.pivotSide = pivotSide;
    }
}
