package org.trade.core.persistent.tradestrategy;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import org.trade.core.aspect.Aspect;

import java.io.Serial;
import java.io.Serializable;


/**
 * TradestrategyContract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
@Entity
@Table(name = "tradestrategy")
public class TradestrategyLite extends Aspect implements Serializable {

    @Serial
    private static final long serialVersionUID = -2181676329258092177L;

    @Column(name = "status", length = 20)
    private String status;

    public TradestrategyLite() {
    }

    /**
     * Constructor for TradestrategyLite. Need for filtered query that just
     * gets the current version
     *
     * @param id      Integer
     * @param version Integer
     */
    public TradestrategyLite(Long id, Integer version) {

        setId(id);
        this.version = version;
    }

    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method setStatus.
     *
     * @param status String
     */
    public void setStatus(String status) {
        this.status = status;
    }

}
