package org.trade.core.persistent.tradestrategy;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import org.trade.core.aspect.Aspect;

import java.io.Serial;
import java.io.Serializable;
import java.time.ZonedDateTime;


/**
 * TradestrategyContract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
@Entity
@Table(name = "tradestrategy")
public class TradestrategyLite extends Aspect implements Serializable {

    @Serial
    private static final long serialVersionUID = -2181676329258092177L;

    @Column(name = "status", length = 20)
    private String status;

    public TradestrategyLite() {
    }

    public TradestrategyLite(Long id, Integer version) {

        super.setId(id);
        super.setVersion(version);
    }

    /**
     * Constructor for TradestrategyLite. Need for filtered query that just
     * gets the current version
     *
     * @param id      Integer
     * @param version Integer
     */
    public TradestrategyLite(Long id, ZonedDateTime createdDate, ZonedDateTime updatedDate, Integer version, Long domainId, String status) {

        super.setId(id);
        super.setCreatedDate(createdDate);
        super.setUpdatedDate(updatedDate);
        super.setVersion(version);
        super.setDomainId(domainId);
        this.setStatus(status);
    }

    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method setStatus.
     *
     * @param status String
     */
    public void setStatus(String status) {
        this.status = status;
    }

}
