package org.trade.core.persistent.tradestrategy;

import org.trade.core.persistent.contract.ContractRecord;
import org.trade.core.persistent.portfolio.PortfolioRecord;
import org.trade.core.persistent.strategy.StrategyRecord;
import org.trade.core.persistent.tradeorder.TradeOrder;
import org.trade.core.persistent.tradeorder.TradeOrderRecord;
import org.trade.core.persistent.tradingday.TradingdayRecord;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * TradestrategyRecord generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradestrategyRecord(Long id,
                                  ZonedDateTime createdDate,
                                  ZonedDateTime updatedDate,
                                  Integer version,
                                  Long domainId,
                                  BigDecimal riskAmount,
                                  Integer chartDays,
                                  Integer barSize,
                                  String tier,
                                  String status,
                                  String side,
                                  Boolean trade,
                                  Integer requestId,
                                  StrategyRecord strategy,
                                  PortfolioRecord portfolio,
                                  ContractRecord contract,
                                  TradingdayRecord tradingday,
                                  List<TradeOrderRecord> tradeOrders) {


    public static TradestrategyRecord from(Tradestrategy tradestrategy) {

        List<TradeOrderRecord> tradeOrderRecords = new ArrayList<>();

        if (null != tradestrategy.getTradeOrders() && !tradestrategy.getTradeOrders().isEmpty()) {

            for (TradeOrder tradeOrder : tradestrategy.getTradeOrders()) {

                tradeOrderRecords.add(TradeOrderRecord.from(tradeOrder));
            }
        }

        return new TradestrategyRecord(
                tradestrategy.getId(),
                tradestrategy.getCreatedDate(),
                tradestrategy.getUpdatedDate(),
                tradestrategy.getVersion(),
                tradestrategy.getDomainId(),
                tradestrategy.getRiskAmount(),
                tradestrategy.getChartDays(),
                tradestrategy.getBarSize(),
                tradestrategy.getTier(),
                tradestrategy.getStatus(),
                tradestrategy.getSide(),
                tradestrategy.getTrade(),
                tradestrategy.getRequestId(),
                (null == tradestrategy.getStrategy() ? null : StrategyRecord.from(tradestrategy.getStrategy())),
                (null == tradestrategy.getPortfolio() ? null : PortfolioRecord.from(tradestrategy.getPortfolio())),
                (null == tradestrategy.getContract() ? null : ContractRecord.from(tradestrategy.getContract())),
                (null == tradestrategy.getTradingday() ? null : TradingdayRecord.from(tradestrategy.getTradingday())),
                List.copyOf(tradeOrderRecords)
        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getRequestId.
     *
     * @return Integer
     */
    public Integer getRequestId() {

        return this.requestId;
    }

    /**
     * Method getBarSize.
     *
     * @return Integer
     */
    public Integer getBarSize() {
        return this.barSize;
    }

    /**
     * Method getChartDays.
     *
     * @return Integer
     */
    public Integer getChartDays() {
        return this.chartDays;
    }

    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method getRiskAmount.
     *
     * @return BigDecimal
     */
    public BigDecimal getRiskAmount() {
        return this.riskAmount;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }

    /**
     * Method getTier.
     *
     * @return String
     */
    public String getTier() {
        return this.tier;
    }

    /**
     * Method getContract.
     *
     * @return ContractRecord
     */
    public ContractRecord getContract() {
        return this.contract;
    }

    /**
     * Method getTradingday.
     *
     * @return TradingdayRecord
     */
    public TradingdayRecord getTradingday() {
        return this.tradingday;
    }

    /**
     * Method getStrategy.
     *
     * @return StrategyRecord
     */
    public StrategyRecord getStrategy() {
        return this.strategy;
    }

    /**
     * Method getPortfolio.
     *
     * @return PortfolioRecord
     */
    public PortfolioRecord getPortfolio() {
        return this.portfolio;
    }

    /**
     * Method getTrade.
     *
     * @return Boolean
     */
    public Boolean getTrade() {

        return this.trade;
    }

    /**
     * Method getTradeOrders.
     *
     * @return List<TradeOrderRecord>
     */
    public List<TradeOrderRecord> getTradeOrders() {
        return this.tradeOrders;
    }
}
