package org.trade.core.persistent.tradestrategy;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import org.trade.core.aspect.Aspect;
import org.trade.core.persistent.contract.ContractLite;
import org.trade.core.persistent.tradeorder.TradeOrder;
import org.trade.core.persistent.tradeposition.TradePosition;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * TradestrategyOrders generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
@Entity
@Table(name = "tradestrategy")
public class TradestrategyOrders extends Aspect implements Serializable {

    @Serial
    private static final long serialVersionUID = -2181676329258092177L;

    @Column(name = "status", length = 20)
    private String status;

    @ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.REFRESH})
    @JoinColumn(name = "contract_id", insertable = false, updatable = false, nullable = false)
    private ContractLite contractLite;

    @OneToMany(mappedBy = "tradestrategy", fetch = FetchType.EAGER, cascade = {CascadeType.REFRESH})
    private List<TradeOrder> tradeOrders = new ArrayList<>(0);

    public TradestrategyOrders() {
    }

    /**
     * Method getContract.
     *
     * @return ContractLite
     */
    public ContractLite getContractLite() {
        return this.contractLite;
    }

    /**
     * Method setContract.
     *
     * @param contractLite ContractId
     */
    public void setContractLite(ContractLite contractLite) {
        this.contractLite = contractLite;
    }

    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method setStatus.
     *
     * @param status String
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Method getTradeOrders.
     *
     * @return List<Trade>
     */
    public List<TradeOrder> getTradeOrders() {
        return this.tradeOrders;
    }

    /**
     * Method setTradeOrders.
     *
     * @param tradeOrders List<TradeOrder>
     */
    public void setTradeOrders(List<TradeOrder> tradeOrders) {
        this.tradeOrders = tradeOrders;
    }

    /**
     * Method addTradeOrder.
     *
     * @param tradeOrders TradeOrder
     */
    public void addTradeOrder(TradeOrder tradeOrders) {
        this.tradeOrders.add(tradeOrders);
    }

    /**
     * Method getOpenTradePosition.
     *
     * @return TradePosition
     */
    @Transient
    public TradePosition getOpenTradePosition() {
        return this.getContractLite().getTradePosition();
    }

    /**
     * Method hasOpenTradePosition.
     *
     * @return boolean
     */
    public boolean hasOpenTradePosition() {
        return null != getOpenTradePosition();
    }
}
