package org.trade.core.persistent.tradestrategy;

import java.time.ZonedDateTime;


/**
 * TradestrategyLiteRecord generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradestrategyLiteRecord(Long id,
                                      ZonedDateTime createdDate,
                                      ZonedDateTime updatedDate,
                                      Integer version,
                                      Long domainId,
                                      String status) {

    public static TradestrategyLiteRecord from(Tradestrategy tradestrategy) {

        return new TradestrategyLiteRecord(

                tradestrategy.getId(),
                tradestrategy.getCreatedDate(),
                tradestrategy.getUpdatedDate(),
                tradestrategy.getVersion(),
                tradestrategy.getDomainId(),
                tradestrategy.getStatus()
        );
    }

    public static TradestrategyLiteRecord from(TradestrategyLite tradestrategy) {

        return new TradestrategyLiteRecord(

                tradestrategy.getId(),
                tradestrategy.getCreatedDate(),
                tradestrategy.getUpdatedDate(),
                tradestrategy.getVersion(),
                tradestrategy.getDomainId(),
                tradestrategy.getStatus()
        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }


    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

}
