package org.trade.core.persistent.dao.series.indicator.vwap;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class Vwap implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7644763985378994305L;

    private BigDecimal vwapPrice;

    public Vwap() {
    }

    /**
     * Constructor for Vwap.
     *
     * @param vwapPrice BigDecimal
     */
    public Vwap(BigDecimal vwapPrice) {
        this.vwapPrice = vwapPrice;
    }

    /**
     * Method getVwapPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getVwapPrice() {
        return this.vwapPrice;
    }

    /**
     * Method setVwapPrice.
     *
     * @param vwapPrice BigDecimal
     */
    public void setVwapPrice(BigDecimal vwapPrice) {
        this.vwapPrice = vwapPrice;
    }

}
