package org.trade.core.persistent.tradingday;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.tradestrategy.TradestrategyRecord;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Tradingday generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradingdayRecord(Long id,
                               ZonedDateTime createdDate,
                               ZonedDateTime updatedDate,
                               Integer version,
                               Long domainId,
                               ZonedDateTime open,
                               ZonedDateTime close,
                               String marketBar,
                               String marketBias,
                               String marketGap,
                               Integer requestId,
                               List<TradestrategyRecord> tradestrategies) {

    public static TradingdayRecord from(Tradingday tradingday) {

        List<TradestrategyRecord> tradestrategyRecords = new ArrayList<>();
/*
        if (null != tradingday.getTradestrategies() && !tradingday.getTradestrategies().isEmpty()) {

            for (Tradestrategy tradestrategy : tradingday.getTradestrategies()) {

                tradestrategyRecords.add(TradestrategyRecord.from(tradestrategy));
            }
        }
*/
        return new TradingdayRecord(
                tradingday.getId(),
                tradingday.getCreatedDate(),
                tradingday.getUpdatedDate(),
                tradingday.getVersion(),
                tradingday.getDomainId(),
                tradingday.getOpen(),
                tradingday.getClose(),
                tradingday.getMarketBar(),
                tradingday.getMarketBias(),
                tradingday.getMarketGap(),
                tradingday.getRequestId(),
                List.copyOf(tradestrategyRecords));
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getOpen.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOpen() {
        return this.open;
    }

    /**
     * Method getClose.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getClose() {
        return this.close;
    }

    /**
     * Method getMarketBias.
     *
     * @return String
     */
    public String getMarketBias() {
        return this.marketBias;
    }

    /**
     * Method getMarketGap.
     *
     * @return String
     */
    public String getMarketGap() {
        return this.marketGap;
    }

    /**
     * Method getMarketBar.
     *
     * @return String
     */
    public String getMarketBar() {
        return this.marketBar;
    }

    /**
     * Method getTradestrategies.
     *
     * @return List<TradestrategyRecord>
     */
    public List<TradestrategyRecord> getTradestrategies() {
        return this.tradestrategies;
    }
}