package org.trade.core.persistent.tradingday;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import java.time.ZonedDateTime;


/**
 * Tradingday generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradingdayRecord(Long id,
                               ZonedDateTime createdDate,
                               ZonedDateTime updatedDate,
                               Integer version,
                               Long domainId,
                               ZonedDateTime open,
                               ZonedDateTime close,
                               String marketBar,
                               String marketBias,
                               String marketGap,
                               Integer requestId) {

    public static TradingdayRecord from(Tradingday tradingday) {

        return new TradingdayRecord(
                tradingday.getId(),
                tradingday.getCreatedDate(),
                tradingday.getUpdatedDate(),
                tradingday.getVersion(),
                tradingday.getDomainId(),
                tradingday.getOpen(),
                tradingday.getClose(),
                tradingday.getMarketBar(),
                tradingday.getMarketBias(),
                tradingday.getMarketGap(),
                tradingday.getRequestId());
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }
}