package org.trade.core.persistent.tradingday;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import java.time.ZonedDateTime;


/**
 * Tradingday generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradingdayRecord(Long id, ZonedDateTime open, ZonedDateTime close, String marketBar, String marketBias,
                               String marketGap, Integer requestId) {

    public static TradingdayRecord from(Tradingday tradingday) {

        return new TradingdayRecord(
                tradingday.getId(),
                tradingday.getOpen(),
                tradingday.getClose(),
                tradingday.getMarketBar(),
                tradingday.getMarketBias(),
                tradingday.getMarketGap(),
                tradingday.getRequestId());
    }
}