package org.trade.core.persistent.candle;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.contract.ContractRecord;

import java.math.BigDecimal;
import java.time.ZonedDateTime;


/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record CandleRecord(Long id, ZonedDateTime startPeriod,
                           ZonedDateTime endPeriod,
                           BigDecimal open,
                           BigDecimal close,
                           BigDecimal high,
                           BigDecimal low,
                           String period,
                           Integer tradeCount,
                           Long volume,
                           BigDecimal vwap,
                           Integer barSize,
                           ZonedDateTime lastUpdateDate,
                           ContractRecord contract) {
    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param candle Candle
     * @return CandleRecord
     */
    public static CandleRecord from(final Candle candle) {

        return new CandleRecord(
                candle.getId(),
                candle.getStartPeriod(),
                candle.getEndPeriod(),
                candle.getOpen(),
                candle.getClose(),
                candle.getHigh(),
                candle.getLow(),
                candle.getPeriod(),
                candle.getTradeCount(),
                candle.getVolume(),
                candle.getVwap(),
                candle.getBarSize(),
                candle.getLastUpdateDate(),
                ContractRecord.from(candle.getContract())
        );
    }
}
