# Software version
component.name.base=Trade Manager
component.name.version=1.0
component.name.date=06/01/2026

# Implementation of the trade manager interface
Broker=org.trade.core.broker.TWSBrokerModel
BrokerTest=org.trade.core.broker.BackTestBrokerModel
PersistentModel=org.trade.core.persistent.TradeServiceImpl

INITIAL_HELP_FILE_NAME=help/index.html
