<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.trade</groupId>
        <artifactId>trade-manager</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>trade-manager-core</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Trade Manager - Core</name>
    <description>Trade Manager core components</description>
    <properties>
        <com.interactivebrokers.tws-api.version>10.20.01</com.interactivebrokers.tws-api.version>
        <org.json.json.version>20251224</org.json.json.version>
        <maven-jar-plugin.version>3.5.0</maven-jar-plugin.version>
        <properties-maven-plugin.version>1.3.0</properties-maven-plugin.version>
        <sql-maven-plugin.version>3.0.0</sql-maven-plugin.version>
        <mariadb-java-client.version>3.5.8</mariadb-java-client.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${org.json.json.version}</version>
        </dependency>
        <dependency>
            <groupId>com.interactivebrokers</groupId>
            <artifactId>tws-api</artifactId>
            <version>${com.interactivebrokers.tws-api.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven-jar-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- Used to load params for sql:execute -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>${properties-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${basedir}/../db.properties</file>
                            </files>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Used to build the database i.e. run sql -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>sql-maven-plugin</artifactId>
                <version>${sql-maven-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>sql-maven-plugin</artifactId>
                        <version>${sql-maven-plugin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.mariadb.jdbc</groupId>
                        <artifactId>mariadb-java-client</artifactId>
                        <version>${mariadb-java-client.version}</version>
                    </dependency>
                </dependencies>
                <!-- Must run initialize first i.e. initialize sql:execute -->
                <configuration>
                    <driver>org.mariadb.jdbc.Driver</driver>
                    <url>${db-dba.url}?serverTimezone=${db-dba.time_zone}</url>
                    <username>${db-dba.username}</username>
                    <password>${db-dba.password}</password>
                    <settingsKey>sensibleKey</settingsKey>
                    <!--all executions are ignored if -Dmaven.test.skip=true-->
                    <skip>false</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <delimiter>//</delimiter>
                            <autocommit>true</autocommit>
                            <srcFiles>
                                <srcFile>target/classes/schema/schema-ddl.sql</srcFile>
                                <srcFile>target/classes/schema/drop-create-user.sql</srcFile>
                                <srcFile>target/classes/schema/default-data.sql</srcFile>
                                <!-- Demo data for 2025 comment out if not needed
                                <srcFile>target/classes/schema/demo-data.sql</srcFile>
                                -->
                            </srcFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>