package org.trade.core.persistent.tradeposition;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.contract.ContractLiteRecord;
import org.trade.core.persistent.tradeorder.TradeOrder;
import org.trade.core.persistent.tradeorder.TradeOrderRecord;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Trade generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradePositionRecord(Long id,
                                  ZonedDateTime createdDate,
                                  ZonedDateTime updatedDate,
                                  Integer version,
                                  Long domainId,
                                  ZonedDateTime openDate,
                                  String side,
                                  Integer openQuantity,
                                  ZonedDateTime closeDate,
                                  BigDecimal totalCommission,
                                  Integer totalBuyQuantity,
                                  BigDecimal totalBuyValue,
                                  Integer totalSellQuantity,
                                  BigDecimal totalSellValue,
                                  BigDecimal totalNetValue,
                                  ContractLiteRecord contract,
                                  List<TradeOrderRecord> tradeOrders) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param tradePosition TradePosition
     * @return TradePositionRecord
     */
    public static TradePositionRecord from(final TradePosition tradePosition) {


        List<TradeOrderRecord> tradeOrderRecords = new ArrayList<>();


        if (null != tradePosition.getTradeOrders() && !tradePosition.getTradeOrders().isEmpty()) {

            for (TradeOrder tradeOrder : tradePosition.getTradeOrders()) {

                tradeOrderRecords.add(TradeOrderRecord.from(tradeOrder));
            }
        }


        return new TradePositionRecord(
                tradePosition.getId(),
                tradePosition.getCreatedDate(),
                tradePosition.getUpdatedDate(),
                tradePosition.getVersion(),
                tradePosition.getDomainId(),
                tradePosition.getOpenDate(),
                tradePosition.getSide(),
                tradePosition.getOpenQuantity(),
                tradePosition.getCloseDate(),
                tradePosition.getTotalCommission(),
                tradePosition.getTotalBuyQuantity(),
                tradePosition.getTotalBuyValue(),
                tradePosition.getTotalSellQuantity(),
                tradePosition.getTotalSellValue(),
                tradePosition.getTotalNetValue(),
                (null != tradePosition.getContractLite() ? ContractLiteRecord.from(tradePosition.getContractLite()) : null),
                List.copyOf(tradeOrderRecords)

        );
    }

    /**
     * There can only ever be one TradePosition open at a time for a Contract. A
     * TradePosition is created when at least one TradeOrder becomes
     * filled/partially filled.
     * <p>
     * The TradeOrder that caused the TradePosition to be created is marked as
     * the opening TradeOrder.
     * <p>
     * A TradePosition is closed when the total open quantity i.e. buy quantity
     * less sell quantity equals zero. At this point the net value represents
     * the P/L for the position.
     */

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getContractLite.
     *
     * @return ContractLiteRecord
     */
    public ContractLiteRecord getContractLite() {
        return this.contract;
    }

    /**
     * Method getPositionOpenDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOpenDate() {
        return this.openDate;
    }

    /**
     * Method getPositionCloseDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCloseDate() {
        return this.closeDate;
    }

    /**
     * Method getOpenQuantity.
     *
     * @return Integer
     */
    public Integer getOpenQuantity() {
        return this.openQuantity;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }


    /**
     * Method getTotalCommission.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalCommission() {
        return this.totalCommission;
    }


    /**
     * Method getTotalBuyQuantity.
     *
     * @return Integer
     */
    public Integer getTotalBuyQuantity() {
        return this.totalBuyQuantity;
    }


    /**
     * Method getTotalSellQuantity.
     *
     * @return Integer
     */
    public Integer getTotalSellQuantity() {
        return this.totalSellQuantity;
    }


    /**
     * Method getTotalBuyValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalBuyValue() {
        return this.totalBuyValue;
    }

    /**
     * Method getTotalSellValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalSellValue() {
        return this.totalSellValue;
    }

    /**
     * Method getTotalNetValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalNetValue() {
        return this.totalNetValue;
    }


    /**
     * Method getTradeOrders.
     *
     * @return List<TradeOrderRecord>
     */
    public List<TradeOrderRecord> getTradeOrders() {

        return this.tradeOrders;
    }
}
