package org.trade.core.persistent.account;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.portfolio.PortfolioRecord;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * Account generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record AccountRecord(Long id, String name, String accountNumber, String currency, String alias,
                            String accountType, BigDecimal availableFunds, BigDecimal buyingPower,
                            BigDecimal cashBalance,
                            BigDecimal grossPositionValue,
                            BigDecimal realizedPnL,
                            BigDecimal unrealizedPnL,
                            List<PortfolioRecord> portfolios) {

    /**
     * Method from note portfolio are LAZY loaded.
     *
     * @param account Account
     * @return AccountRecord
     */
    public static AccountRecord from(Account account) {

        List<PortfolioRecord> portfolioRecords = new ArrayList<>();

        /*
        if (null != account.getPortfolios() && !account.getPortfolios().isEmpty()) {

            for (Portfolio portfolio : account.getPortfolios()) {

                portfolioRecords.add(PortfolioRecord.from(portfolio));
            }
        }
*/
        return new AccountRecord(
                account.getId(),
                account.getName(),
                account.getAccountNumber(),
                account.getCurrency(),
                account.getAlias(),
                account.getAccountType(),
                account.getAvailableFunds(),
                account.getBuyingPower(),
                account.getCashBalance(),
                account.getGrossPositionValue(),
                account.getRealizedPnL(),
                account.getUnrealizedPnL(),
                List.copyOf(portfolioRecords)
        );
    }
}
