package org.trade.core.persistent.tradeorder;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.tradeorderfill.TradeOrderfill;
import org.trade.core.persistent.tradeorderfill.TradeOrderfillRecord;
import org.trade.core.persistent.tradeposition.TradePositionRecord;
import org.trade.core.persistent.tradestrategy.TradestrategyLiteRecord;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Order generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradeOrderRecord(Long id,
                               ZonedDateTime createdDate,
                               ZonedDateTime updatedDate,
                               Integer version,
                               Long domainId,
                               Boolean active,
                               String accountNumber,
                               String action,
                               String orderType,
                               Integer quantity,
                               String timeInForce,
                               ZonedDateTime orderCreateDate,
                               ZonedDateTime orderUpdateDate,
                               Integer triggerMethod,
                               Integer overrideConstraints,
                               String status,
                               BigDecimal stopPrice,
                               BigDecimal auxPrice,
                               Boolean transmit,
                               BigDecimal trailStopPrice,
                               BigDecimal trailingPercent,
                               String warningMessage,
                               String whyHeld,
                               BigDecimal averageFilledPrice,
                               Boolean allOrNothing,
                               Integer clientId,
                               BigDecimal commission,
                               Integer displayQuantity,
                               String FAGroup,
                               String FAProfile,
                               String FAMethod,
                               BigDecimal FAPercent,
                               Integer filledQuantity,
                               ZonedDateTime filledDate,
                               ZonedDateTime goodAfterTime,
                               ZonedDateTime goodTillTime,
                               Boolean hidden,
                               Boolean isOpenPosition,
                               Boolean isFilled,
                               BigDecimal limitPrice,
                               String ocaGroupName,
                               Integer ocaType,
                               Integer orderKey,
                               String orderReference,
                               Integer permId,
                               Integer parentId,
                               List<TradeOrderfillRecord> tradeOrderfills,
                               TradePositionRecord tradePosition,
                               TradestrategyLiteRecord tradestrategyLite) {


    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param tradeOrder TradeOrder
     * @return TradeOrderRecord
     */
    public static TradeOrderRecord from(final TradeOrder tradeOrder) {


        List<TradeOrderfillRecord> tradeOrderfillRecords = new ArrayList<>();

        if (null != tradeOrder.getTradeOrderfills() && !tradeOrder.getTradeOrderfills().isEmpty()) {

            for (TradeOrderfill tradeOrderfill : tradeOrder.getTradeOrderfills()) {

                tradeOrderfillRecords.add(TradeOrderfillRecord.from(tradeOrderfill, false));
            }
        }

        return new TradeOrderRecord(
                tradeOrder.getId(),
                tradeOrder.getCreatedDate(),
                tradeOrder.getUpdatedDate(),
                tradeOrder.getVersion(),
                tradeOrder.getDomainId(),
                tradeOrder.isActive(),
                tradeOrder.getAccountNumber(),
                tradeOrder.getAction(),
                tradeOrder.getOrderType(),
                tradeOrder.getQuantity(),
                tradeOrder.getTimeInForce(),
                tradeOrder.getOrderCreateDate(),
                tradeOrder.getOrderUpdateDate(),
                tradeOrder.getTriggerMethod(),
                tradeOrder.getOverrideConstraints(),
                tradeOrder.getStatus(),
                tradeOrder.getStopPrice(),
                tradeOrder.getAuxPrice(),
                tradeOrder.getTransmit(),
                tradeOrder.getTrailStopPrice(),
                tradeOrder.getTrailingPercent(),
                tradeOrder.getWarningMessage(),
                tradeOrder.getWhyHeld(),
                tradeOrder.getAverageFilledPrice(),
                tradeOrder.getAllOrNothing(),
                tradeOrder.getClientId(),
                tradeOrder.getCommission(),
                tradeOrder.getDisplayQuantity(),
                tradeOrder.getFAGroup(),
                tradeOrder.getFAProfile(),
                tradeOrder.getFAMethod(),
                tradeOrder.getFAPercent(),
                tradeOrder.getFilledQuantity(),
                tradeOrder.getFilledDate(),
                tradeOrder.getGoodAfterTime(),
                tradeOrder.getGoodTillTime(),
                tradeOrder.getHidden(),
                tradeOrder.getIsOpenPosition(),
                tradeOrder.getIsFilled(),
                tradeOrder.getLimitPrice(),
                tradeOrder.getOcaGroupName(),
                tradeOrder.getOcaType(),
                tradeOrder.getOrderKey(),
                tradeOrder.getOrderReference(),
                tradeOrder.getPermId(),
                tradeOrder.getParentId(),
                List.copyOf(tradeOrderfillRecords),
                (null != tradeOrder.getTradePosition() ? TradePositionRecord.from(tradeOrder.getTradePosition()) : null),
                (null != tradeOrder.getTradestrategyLite() ? TradestrategyLiteRecord.from(tradeOrder.getTradestrategyLite()) : null)

        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getActive
     *
     * @return Boolean
     */
    public Boolean getActive() {

        return this.active;
    }

    /**
     * Method getTradePosition.
     *
     * @return TradePositionRecord
     */
    public TradePositionRecord getTradePosition() {
        return this.tradePosition;
    }

    /**
     * Method getTradestrategy.
     *
     * @return TradestrategyLiteRecord
     */
    public TradestrategyLiteRecord getTradestrategyLite() {
        return this.tradestrategyLite;
    }

    /**
     * Method getAction.
     *
     * @return String
     */
    public String getAction() {
        return this.action;
    }

    /**
     * Method getAccountNumber.
     *
     * @return String
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Method getAllOrNothing.
     *
     * @return Boolean
     */
    public Boolean getAllOrNothing() {
        return this.allOrNothing;
    }

    /**
     * Method getAuxPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getAuxPrice() {
        return this.auxPrice;
    }

    /**
     * Method getAverageFilledPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getAverageFilledPrice() {
        return this.averageFilledPrice;
    }

    /**
     * Method getClientId.
     *
     * @return Integer
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Method getCommission.
     *
     * @return BigDecimal
     */
    public BigDecimal getCommission() {
        return this.commission;
    }

    /**
     * Method getOrderCreateDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOrderCreateDate() {
        return this.orderCreateDate;
    }

    /**
     * Method getDisplayQuantity.
     *
     * @return Integer
     */
    public Integer getDisplayQuantity() {
        return this.displayQuantity;
    }

    /**
     * Method getFAGroup.
     *
     * @return String
     */
    public String getFAGroup() {
        return this.FAGroup;
    }

    /**
     * Method getFAProfile.
     *
     * @return String
     */
    public String getFAProfile() {
        return this.FAProfile;
    }

    /**
     * Method getFAMethod.
     *
     * @return String
     */
    public String getFAMethod() {
        return this.FAMethod;
    }

    /**
     * Method getFAPercent.
     *
     * @return BigDecimal
     */
    public BigDecimal getFAPercent() {
        return this.FAPercent;
    }

    /**
     * Method getFilledDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getFilledDate() {
        return this.filledDate;
    }

    /**
     * Method getFilledQuantity.
     *
     * @return Integer
     */
    public Integer getFilledQuantity() {
        return this.filledQuantity;
    }

    /**
     * Method getGoodAfterTime.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getGoodAfterTime() {
        return this.goodAfterTime;
    }

    /**
     * Method getGoodTillTime.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getGoodTillTime() {
        return this.goodTillTime;
    }

    /**
     * Method getHidden.
     *
     * @return Boolean
     */
    public Boolean getHidden() {
        return this.hidden;
    }

    /**
     * Method getIsOpenPosition.
     *
     * @return Boolean
     */
    public Boolean getIsOpenPosition() {
        return this.isOpenPosition;
    }

    /**
     * Method getIsFilled.
     *
     * @return Boolean
     */
    public Boolean getIsFilled() {
        return this.isFilled;
    }

    /**
     * Method getLimitPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getLimitPrice() {
        return this.limitPrice;
    }

    /**
     * Method getOcaGroupName.
     *
     * @return String
     */
    public String getOcaGroupName() {
        return this.ocaGroupName;
    }

    /**
     * Method getOcaType.
     *
     * @return Integer
     */

    public Integer getOcaType() {
        return this.ocaType;
    }

    /**
     * Method getOrderKey.
     *
     * @return Integer
     */
    public Integer getOrderKey() {
        return this.orderKey;
    }

    /**
     * Method getOrderReference.
     *
     * @return String
     */
    public String getOrderReference() {
        return this.orderReference;
    }

    /**
     * Method getOrderType.
     *
     * @return String
     */
    public String getOrderType() {
        return this.orderType;
    }

    /**
     * Method getOverrideConstraints.
     *
     * @return Integer
     */
    public Integer getOverrideConstraints() {
        return this.overrideConstraints;
    }

    /**
     * Method getParentId.
     *
     * @return Integer
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * Method getPermId.
     *
     * @return Integer
     */
    public Integer getPermId() {
        return this.permId;
    }

    /**
     * Method getQuantity.
     *
     * @return Integer
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Method getTimeInForce.
     *
     * @return String
     */
    public String getTimeInForce() {
        return this.timeInForce;
    }

    /**
     * Method getStatus.
     * <p>
     * The order status. Possible values include:
     * <p>
     * - PendingSubmit - indicates that you have transmitted the order, but have
     * not yet received confirmation that it has been accepted by the order
     * destination. NOTE: This order status is not sent by TWS and should be
     * explicitly set by the API developer when an order is submitted.
     * <p>
     * - PendingCancel - indicates that you have sent a request to cancel the
     * order but have not yet received cancel confirmation from the order
     * destination. At this point, your order is not confirmed canceled. You may
     * still receive an execution while your cancellation request is pending.
     * NOTE: This order status is not sent by TWS and should be explicitly set
     * by the API developer when an order is canceled.
     * <p>
     * = PreSubmitted - indicates that a simulated order type has been accepted
     * by the IB system and that this order has yet to be elected. The order is
     * held in the IB system until the election criteria are met. At that time
     * the order is transmitted to the order destination as specified .
     * <p>
     * - Submitted - indicates that your order has been accepted at the order
     * destination and is working.
     * <p>
     * - Cancelled - indicates that the balance of your order has been confirmed
     * canceled by the IB system. This could occur unexpectedly when IB or the
     * destination has rejected your order.
     * <p>
     * - Filled - indicates that the order has been completely filled.
     * <p>
     * - Inactive - indicates that the order has been accepted by the system
     * (simulated orders) or an exchange (native orders) but that currently the
     * order is inactive due to system, exchange or other issues.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method getStopPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getStopPrice() {
        return this.stopPrice;
    }

    /**
     * Method getTransmit.
     *
     * @return Boolean
     */
    public Boolean getTransmit() {
        return this.transmit;
    }

    /**
     * Method getTrailStopPrice.
     *
     * @return BigDecimal
     */

    public BigDecimal getTrailStopPrice() {
        return this.trailStopPrice;
    }

    /**
     * Method getTrailingPercent.
     *
     * @return BigDecimal
     */
    public BigDecimal getTrailingPercent() {
        return this.trailingPercent;
    }

    /**
     * Method getTriggerMethod.
     *
     * @return Integer
     */
    public Integer getTriggerMethod() {
        return this.triggerMethod;
    }

    /**
     * Method getLastUpdateDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOrderUpdateDate() {
        return this.orderUpdateDate;
    }

    /**
     * Method getWarningMessage.
     *
     * @return String
     */
    public String getWarningMessage() {
        return this.warningMessage;
    }

    /**
     * Method getWhyHeld.
     *
     * @return String
     */
    public String getWhyHeld() {
        return this.whyHeld;
    }

    /**
     * Method getTradeOrderfills.
     *
     * @return List<TradeOrderfillRecord>
     */
    public List<TradeOrderfillRecord> getTradeOrderfills() {
        return this.tradeOrderfills;
    }

}
