package org.trade.core.persistent.log;


import java.time.ZonedDateTime;
import java.util.Date;

/**
 * LogRecord generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public record LogRecord(ZonedDateTime timestamp,
                        String level,
                        String thread,
                        String logger,
                        String message
) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param log Log
     * @return LogRecord
     */
    public static LogRecord from(final Log log) {

        return new LogRecord(log.getTimestamp(), log.getLevel(), log.getThread(), log.getLogger(), log.getMessage());
    }

    /**
     * Method getTimestamp.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public String getLevel() {
        return this.level;
    }

    /**
     * Method getThread.
     *
     * @return String
     */
    public String getThread() {
        return this.thread;
    }

    /**
     * Method getLogger
     *
     * @return String
     */
    public String getLogger() {

        return this.logger;
    }

    /**
     * Method getMessage.
     *
     * @return String
     */
    public String getMessage() {

        return this.message;
    }
}