package org.trade.core.persistent.tradeorderfill;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.tradeorder.TradeOrderRecord;

import java.math.BigDecimal;
import java.time.ZonedDateTime;


/**
 * TradeOrderfillRecord generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record TradeOrderfillRecord(Long id,
                                   ZonedDateTime createdDate,
                                   ZonedDateTime updatedDate,
                                   Integer version,
                                   Long domainId,
                                   String accountNumber,
                                   Integer quantity,
                                   String side,
                                   String exchange,
                                   BigDecimal price,
                                   ZonedDateTime time,
                                   BigDecimal averagePrice,
                                   Integer cumulativeQuantity,
                                   String execId,
                                   BigDecimal commission,
                                   String orderReference,
                                   Integer permId,
                                   TradeOrderRecord tradeOrder) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param tradeOrderfill TradeOrderfill
     * @return TradeOrderfillRecord
     */
    public static TradeOrderfillRecord from(final TradeOrderfill tradeOrderfill) {

        return new TradeOrderfillRecord(
                tradeOrderfill.getId(),
                tradeOrderfill.getCreatedDate(),
                tradeOrderfill.getUpdatedDate(),
                tradeOrderfill.getVersion(),
                tradeOrderfill.getDomainId(),
                tradeOrderfill.getAccountNumber(),
                tradeOrderfill.getQuantity(),
                tradeOrderfill.getSide(),
                tradeOrderfill.getExchange(),
                tradeOrderfill.getPrice(),
                tradeOrderfill.getTime(),
                tradeOrderfill.getAveragePrice(),
                tradeOrderfill.getCumulativeQuantity(),
                tradeOrderfill.getExecId(),
                tradeOrderfill.getCommission(),
                tradeOrderfill.getOrderReference(),
                tradeOrderfill.getPermId(),
                null //(null != tradeOrderfill.getTradeOrder() ? TradeOrderRecord.from(tradeOrderfill.getTradeOrder()) : null)
        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getTradeOrder.
     *
     * @return TradeOrderRecord
     */
    public TradeOrderRecord getTradeOrder() {
        return this.tradeOrder;
    }


    /**
     * Method getAccountNumber.
     *
     * @return String
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Method getAveragePrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getAveragePrice() {
        return this.averagePrice;
    }

    /**
     * Method getCommission.
     *
     * @return BigDecimal
     */
    public BigDecimal getCommission() {
        return this.commission;
    }

    /**
     * Method getCumulativeQuantity.
     *
     * @return Integer
     */
    public Integer getCumulativeQuantity() {
        return this.cumulativeQuantity;
    }

    /**
     * Method getExecId.
     *
     * @return String
     */
    public String getExecId() {
        return this.execId;
    }

    /**
     * Method getOrderReference.
     *
     * @return String
     */
    public String getOrderReference() {
        return this.orderReference;
    }

    /**
     * Method getExchange.
     *
     * @return String
     */
    public String getExchange() {
        return this.exchange;
    }

    /**
     * Method getPermId.
     *
     * @return Integer
     */
    public Integer getPermId() {
        return this.permId;
    }

    /**
     * Method getPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Method getQuantity.
     *
     * @return Integer
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }

    /**
     * Method getTime.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getTime() {
        return this.time;
    }

}
