package org.trade.core.persistent.dao.series.indicator.cci;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public class CommodityChannelIndex implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7644763985378994305L;

    private BigDecimal cciAverage;

    public CommodityChannelIndex() {
    }

    /**
     * Constructor for MovingAverage.
     *
     * @param cciAverage BigDecimal
     */
    public CommodityChannelIndex(BigDecimal cciAverage) {
        this.cciAverage = cciAverage;
    }

    /**
     * Method getMovingAverage.
     *
     * @return BigDecimal
     */
    public BigDecimal getCommodityChannelIndex() {
        return this.cciAverage;
    }

    /**
     * Method setMovingAverage.
     *
     * @param cciAverage BigDecimal
     */
    public void setCommodityChannelIndex(BigDecimal cciAverage) {
        this.cciAverage = cciAverage;
    }

}
