spring.application.name=trade-api

# Root API point
spring.data.rest.base-path=/api

# Springdoc swagger ui to exclude/include
springdoc.api-docs.enabled=true
springdoc.packages-to-exclude = org.trade.core
springdoc.paths-to-match = /api/**, /public/**, /auth/**

app.cors.allowed-origins=http://localhost:8080
app.cors.allowedMethods="GET,POST,PUT,DELETE,OPTIONS"
app.cors.allowedHeaders="*"
app.cors.allowCredentials=true
app.cors.maxAge=3600

# The location of the logging properties.
logging.config=file:../config.properties

# Spring datasource connection info see ../db.properties
spring.datasource.url=@db-dba.url@/@db-dba.schema@?serverTimezone=@db-dba.time_zone@
spring.datasource.name=@db-dba.schema@
spring.datasource.serverTimezone=@db-dba.time_zone@
spring.datasource.username=@db-user.username@
spring.datasource.password=@db-user.password@
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# DB connection pool properties
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Defines the number of statements to be grouped in a single batch.
spring.jpa.properties.hibernate.jdbc.batch_size=20

# Optimizes batching by ordering operations.
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Enables batching for entities with versioning.
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

#Hibernate Configuration
# Show or not log for each sql query
spring.jpa.show-sql=false

# Allows Hibernate to generate SQL optimized for a particular DBMS
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
spring.jpa.hibernate.ddl-auto=none

# Spring web request interceptor that binds a Hibernate Session to the thread for the entire processing of the request.
spring.jpa.open-in-view=false

#Hibernate Configuration
# Timezone for the DB
spring.jpa.properties.hibernate.jdbc.time_zone=@db-dba.time_zone@
