package org.trade.core.persistent.dao.series.indicator.atr;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serial;
import java.math.BigDecimal;

/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class AverageTrueRange implements java.io.Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7644763985378994305L;

    private BigDecimal averageTrueRange;

    public AverageTrueRange() {
    }

    /**
     * Constructor for AverageTrueRange.
     *
     * @param averageTrueRange BigDecimal
     */
    public AverageTrueRange(BigDecimal averageTrueRange) {
        this.averageTrueRange = averageTrueRange;
    }

    /**
     * Method getAverageTrueRange.
     *
     * @return BigDecimal
     */
    public BigDecimal getAverageTrueRange() {
        return this.averageTrueRange;
    }

    /**
     * Method setAverageTrueRange.
     *
     * @param averageTrueRange BigDecimal
     */
    public void setAverageTrueRange(BigDecimal averageTrueRange) {
        this.averageTrueRange = averageTrueRange;
    }

}
