package org.trade.core.persistent.contract;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import java.time.ZonedDateTime;


/**
 * Contract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public record ContractRecord(Long id, String symbol,
                             String currency,
                             String exchange,
                             ZonedDateTime expiry,
                             String secType,
                             Integer requestId) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param contract Contract
     * @return ContractRecord
     */
    public static ContractRecord from(final Contract contract) {

        return new ContractRecord(
                contract.getId(),
                contract.getSymbol(),
                contract.getCurrency(),
                contract.getExchange(),
                contract.getExpiry(),
                contract.getSecType(),
                contract.getRequestId()
        );
    }
}