package org.trade.core.persistent.contract;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import java.time.ZonedDateTime;


/**
 * Contract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public record ContractRecord(Long id, ZonedDateTime createdDate,
                             ZonedDateTime updatedDate,
                             Integer version,
                             Long domainId,
                             String symbol,
                             String currency,
                             String exchange,
                             ZonedDateTime expiry,
                             String secType,
                             Integer requestId) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param contract Contract
     * @return ContractRecord
     */
    public static ContractRecord from(final Contract contract) {

        return new ContractRecord(
                contract.getId(),
                contract.getCreatedDate(),
                contract.getUpdatedDate(),
                contract.getVersion(),
                contract.getDomainId(),
                contract.getSymbol(),
                contract.getCurrency(),
                contract.getExchange(),
                contract.getExpiry(),
                contract.getSecType(),
                contract.getRequestId()
        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getRequestId.
     *
     * @return Integer
     */
    public Integer getRequestId() {

        return this.requestId;
    }

    /**
     * Method getCurrency.
     *
     * @return String
     */
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Method getExchange.
     *
     * @return String
     */
    public String getExchange() {
        return this.exchange;
    }

    /**
     * Method getExpiry.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getExpiry() {
        return this.expiry;
    }

    /**
     * Method getSymbol.
     *
     * @return String
     */
    public String getSymbol() {
        return this.symbol;
    }

    /**
     * Method getSecType.
     *
     * @return String
     */
    public String getSecType() {
        return this.secType;
    }
}