package org.trade.core.persistent.contract;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.tradeposition.TradePositionRecord;

import java.time.ZonedDateTime;


/**
 * Contract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public record ContractLiteRecord(Long id, ZonedDateTime createdDate,
                                 ZonedDateTime updatedDate,
                                 Integer version,
                                 Long domainId,
                                 TradePositionRecord tradePositionRecord) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param contract Contract
     * @return ContractRecord
     */
    public static ContractLiteRecord from(final ContractLite contract) {

        return new ContractLiteRecord(
                contract.getId(),
                contract.getCreatedDate(),
                contract.getUpdatedDate(),
                contract.getVersion(),
                contract.getDomainId(),
                null //(null != contract.getTradePosition() ? TradePositionRecord.from(contract.getTradePosition()) : null)
        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getDomainId
     *
     * @return TradePositionRecord
     */
    public TradePositionRecord getTradePositionRecord() {

        return this.tradePositionRecord;
    }
}