package org.trade.core.persistent.rule;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * RuleRecord generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record RuleRecord(Long id, String comment,
                         byte[] rule,
                         Integer ruleVersion,
                         String contentType
        /* StrategyRecord strategy */) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param rule Rule
     * @return RuleRecord
     */
    public static RuleRecord from(final Rule rule) {

        return new RuleRecord(
                rule.getId(),
                rule.getComment(),
                rule.getRule(),
                rule.ruleVersion,
                rule.getContentType()
                // rule.getStrategy()
        );
    }
}

