package org.trade.core.persistent.rule;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Pattern;
import org.trade.core.dao.Aspect;
import org.trade.core.persistent.dao.Strategy;
import org.trade.core.util.CoreUtils;
import org.trade.core.valuetype.ContentType;

import java.io.Serial;
import java.io.Serializable;
import java.util.Comparator;
import java.util.Objects;


/**
 * Rule generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
@Entity
@Table(name = "rule")
public class Rule extends Aspect implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 2273276207080568947L;

    @Column(name = "active", length = 1, nullable = false)
    private Boolean active;

    @Column(name = "comment", nullable = false, length = 200)
    private String comment;

    @Lob
    @Column(name = "rule")
    private byte[] rule;

    @Column(name = "rule_version", columnDefinition = "integer DEFAULT 0", nullable = false)
    protected Integer ruleVersion;

    @Column(name = "content_type", length = 20, nullable = false)
    @Pattern(regexp = "^(text/java|text/javascript|text/rtf)$")
    private String contentType = ContentType.JAVA;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "strategy_id", nullable = false)
    private Strategy strategy;

    public Rule() {

    }

    /**
     * Constructor for Rule.
     *
     * @param strategy    Strategy
     * @param active      Boolean
     * @param ruleVersion Integer
     * @param comment     String
     */
    public Rule(Strategy strategy, Boolean active, Integer ruleVersion, String comment) {

        this.strategy = strategy;
        this.active = active;
        this.ruleVersion = ruleVersion;
        this.comment = comment;
    }

    /**
     * Constructor for Rule.
     *
     * @param strategy    Strategy
     * @param active      Boolean
     * @param ruleVersion Integer
     * @param comment     String
     * @param rule        byte[]
     * @param contentType String
     */
    public Rule(Strategy strategy, Boolean active, Integer ruleVersion, String comment, byte[] rule, String contentType) {

        this.strategy = strategy;
        this.active = active;
        this.ruleVersion = ruleVersion;
        this.comment = comment;
        this.rule = rule;
        this.contentType = contentType;
    }

    /**
     * Method getStrategy.
     *
     * @return Strategy
     */
    public Strategy getStrategy() {
        return this.strategy;
    }

    /**
     * Method setStrategy.
     *
     * @param strategy Strategy
     */
    public void setStrategy(Strategy strategy) {
        this.strategy = strategy;
    }

    /**
     * Method getActive.
     *
     * @return Boolean
     */
    public Boolean isActive() {
        return this.active;
    }

    /**
     * Method setActive.
     *
     * @param active Boolean
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * Method getComment.
     *
     * @return String
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Method setComment.
     *
     * @param comment String
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Method getRule.
     *
     * @return byte[]
     */
    public byte[] getRule() {
        return this.rule;
    }

    /**
     * Method setRule.
     *
     * @param rule byte[]
     */
    public void setRule(byte[] rule) {
        this.rule = rule;
    }

    /**
     * Method getRuleVersion.
     *
     * @return Integer
     */
    public Integer getRuleVersion() {
        return this.ruleVersion;
    }

    /**
     * Method getRuleVersion.
     *
     * @param ruleVersion Integer
     */
    public void setRuleVersion(Integer ruleVersion) {
        this.ruleVersion = ruleVersion;
    }

    /**
     * Method getContentType.
     *
     * @return String
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Method setContentType.
     *
     * @param contentType String
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return "Version-" + this.getRuleVersion();
    }

    public static final Comparator<Rule> VERSION_ORDER = (o1, o2) -> CoreUtils.nullSafeComparator(o1.getRuleVersion(), o2.getRuleVersion());

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {
            return true;
        }

        if (objectToCompare instanceof Rule) {

            if (null == this.getId() || null == this.getRuleVersion()) {

                return false;
            }

            return Objects.equals(this.getStrategy().getId(), ((Rule) objectToCompare).getStrategy().getId())
                    && this.getRuleVersion().equals(((Rule) objectToCompare).getRuleVersion());

        }
        return false;
    }
}
