package org.trade.core.persistent.rule;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.persistent.strategy.StrategyRecord;

import java.time.ZonedDateTime;

/**
 * RuleRecord generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record RuleRecord(Long id,
                         ZonedDateTime createdDate,
                         ZonedDateTime updatedDate,
                         Integer version,
                         Long domainId,
                         String comment,
                         byte[] rule,
                         Integer ruleVersion,
                         String contentType,
                         StrategyRecord strategy) {

    /**
     * Method from note roles are LAZY loaded., hence we do not get the children.
     *
     * @param rule Rule
     * @return RuleRecord
     */
    public static RuleRecord from(final Rule rule) {

        return new RuleRecord(
                rule.getId(),
                rule.getCreatedDate(),
                rule.getUpdatedDate(),
                rule.getVersion(),
                rule.getDomainId(),
                rule.getComment(),
                rule.getRule(),
                rule.ruleVersion,
                rule.getContentType(),
                (null != rule.getStrategy() ? StrategyRecord.from(rule.getStrategy(), false) : null));
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }
}

