package org.trade.core.persistent.strategy;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1


import org.trade.core.persistent.rule.RuleRecord;
import org.trade.core.persistent.strategy.series.indicator.IndicatorSeries;
import org.trade.core.persistent.strategy.series.indicator.IndicatorSeriesRecord;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Strategy generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record StrategyRecord(Long id,
                             ZonedDateTime createdDate,
                             ZonedDateTime updatedDate,
                             Integer version,
                             Long domainId,
                             String name,
                             String className,
                             String description,
                             Boolean marketData,
                             StrategyRecord strategyMgr,
                             List<RuleRecord> rules,
                             List<IndicatorSeriesRecord> indicatorSeries) {

    /**
     * Method from note rules are LAZY loaded., hence we do not get the children.
     *
     * @param strategy Strategy
     * @return StrategyRecord
     */
    public static StrategyRecord from(final Strategy strategy) {

        List<RuleRecord> ruleRecords = new ArrayList<>();

        /*
        if (null != strategy.getRules() && !strategy.getRules().isEmpty()) {

            for (Rule rule : strategy.getRules()) {

                ruleRecords.add(RuleRecord.from(rule));
            }
        }

         */

        List<IndicatorSeriesRecord> indicatorSeriesRecords = new ArrayList<>();

        if (null != strategy.getIndicatorSeries() && !strategy.getIndicatorSeries().isEmpty()) {

            for (IndicatorSeries indicatorSeries : strategy.getIndicatorSeries()) {

                indicatorSeriesRecords.add(IndicatorSeriesRecord.from(indicatorSeries));
            }
        }

        return new StrategyRecord(
                strategy.getId(),
                strategy.getCreatedDate(),
                strategy.getUpdatedDate(),
                strategy.getVersion(),
                strategy.getDomainId(),
                strategy.getName(),
                strategy.getClassName(),
                strategy.getDescription(),
                strategy.getMarketData(),
                (null != strategy.getStrategyManager() ? StrategyRecord.from(strategy.getStrategyManager()) : null),
                List.copyOf(ruleRecords),
                indicatorSeriesRecords
        );
    }

    public Long getId() {
        return id;
    }

    /**
     * Method getCreatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Method getUpdatedDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Method getVersion.
     *
     * @return Integer
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * Method getDomainId
     *
     * @return Long
     */
    public Long getDomainId() {

        return domainId;
    }

    /**
     * Method getName.
     *
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Method getClassName.
     *
     * @return String
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Method getDescription.
     *
     * @return String
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Method getMarketData.
     *
     * @return Boolean
     */
    public Boolean getMarketData() {
        return this.marketData;
    }

    /**
     * Method getRules.
     *
     * @return List<RuleRecord>
     */
    public List<RuleRecord> getRules() {
        return this.rules;
    }


    /**
     * Method getIndicatorSeries.
     *
     * @return List<IndicatorSeries>
     */
    public List<IndicatorSeriesRecord> getIndicatorSeries() {
        return this.indicatorSeries;
    }

    /**
     * Method getStrategyManager.
     *
     * @return Strategy
     */
    public StrategyRecord getStrategyManager() {
        return this.strategyMgr;
    }

}
