package org.trade.core.persistent.strategy;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1


import org.trade.core.persistent.dao.series.indicator.IndicatorSeries;
import org.trade.core.persistent.dao.series.indicator.IndicatorSeriesRecord;
import org.trade.core.persistent.rule.Rule;
import org.trade.core.persistent.rule.RuleRecord;

import java.util.ArrayList;
import java.util.List;

/**
 * Strategy generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public record StrategyRecord(Long id, String name,
                             String className,
                             String description,
                             Boolean marketData,
                             StrategyRecord strategyMgr,
                             List<RuleRecord> rules,
                             List<IndicatorSeriesRecord> indicatorSeries) {

    /**
     * Method from note rules are LAZY loaded., hence we do not get the children.
     *
     * @param strategy Strategy
     * @return StrategyRecord
     */
    public static StrategyRecord from(final Strategy strategy) {

        List<RuleRecord> ruleRecords = new ArrayList<>();

        /*
        if (null != strategy.getRules() && !strategy.getRules().isEmpty()) {

            for (Rule rule : strategy.getRules()) {

                ruleRecords.add(RuleRecord.from(rule));
            }
        }

         */

        List<IndicatorSeriesRecord> indicatorSeriesRecords = new ArrayList<>();

        if (null != strategy.getIndicatorSeries() && !strategy.getIndicatorSeries().isEmpty()) {

            for (IndicatorSeries indicatorSeries : strategy.getIndicatorSeries()) {

                indicatorSeriesRecords.add(IndicatorSeriesRecord.from(indicatorSeries));
            }
        }

        return new StrategyRecord(
                strategy.getId(),
                strategy.getName(),
                strategy.getClassName(),
                strategy.getDescription(),
                strategy.getMarketData(),
                (null != strategy.getStrategyManager() ? StrategyRecord.from(strategy.getStrategyManager()) : null),
                ruleRecords,
                indicatorSeriesRecords
        );
    }
}
