/* ===========================================================
 * TradeManager : a application to trade strategies for the Java(tm) platform
 * ===========================================================
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Project Info:  org.trade
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * [Java is a trademark or registered trademark of Oracle, Inc.
 * in the United States and other countries.]
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Original Author:  Simon Allen;
 * Contributor(s):   -;
 *
 * Changes
 * -------
 *
 */
package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.trade.core.dao.Aspect;
import org.trade.core.valuetype.AccountType;
import org.trade.core.valuetype.Currency;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * Account generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class AccountDto extends Aspect implements Serializable, Cloneable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 5891080561163346464L;

    private String name;
    private String accountNumber;
    private String currency;
    private String alias;
    private String accountType;
    private BigDecimal availableFunds = new BigDecimal(0);
    private BigDecimal buyingPower = new BigDecimal(0);
    private BigDecimal cashBalance = new BigDecimal(0);
    private BigDecimal grossPositionValue = new BigDecimal(0);
    private BigDecimal realizedPnL = new BigDecimal(0);
    private BigDecimal unrealizedPnL = new BigDecimal(0);
    private List<PortfolioDto> portfolios = new ArrayList<>(0);

    public AccountDto() {

        this.accountType = AccountType.INDIVIDUAL;
        this.currency = Currency.USD;
    }

    /**
     * Constructor for Account.
     *
     * @param name          String
     * @param accountNumber String
     * @param currency      String
     * @param accountType   String
     */
    public AccountDto(String name, String accountNumber, String currency, String accountType) {

        this.accountNumber = accountNumber;
        this.accountType = accountType;
        this.name = name;
        this.currency = currency;
    }

    /**
     * Constructor for Account.
     *
     * @param accountNumber      String
     * @param name               String
     * @param availableFunds     BigDecimal
     * @param buyingPower        BigDecimal
     * @param cashBalance        BigDecimal
     * @param currency           String
     * @param grossPositionValue BigDecimal
     * @param realizedPnL        BigDecimal
     * @param unrealizedPnL      BigDecimal
     */
    public AccountDto(String accountNumber, String name, String accountType, BigDecimal availableFunds,
                      BigDecimal buyingPower, BigDecimal cashBalance, String currency, BigDecimal grossPositionValue,
                      BigDecimal realizedPnL, BigDecimal unrealizedPnL) {

        this.accountNumber = accountNumber;
        this.accountType = accountType;
        this.name = name;
        this.availableFunds = availableFunds;
        this.buyingPower = buyingPower;
        this.cashBalance = cashBalance;
        this.currency = currency;
        this.grossPositionValue = grossPositionValue;
        this.realizedPnL = realizedPnL;
        this.unrealizedPnL = unrealizedPnL;
    }

    /**
     * Method getName.
     *
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Method setName.
     *
     * @param name String
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Method getAccountNumber.
     *
     * @return String
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Method setAccountNumber.
     *
     * @param accountNumber String
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Method getAccountType.
     *
     * @return String
     */
    public String getAccountType() {
        return this.accountType;
    }

    /**
     * Method setAccountType.
     *
     * @param accountType String
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * Method getAlias.
     *
     * @return String
     */
    public String getAlias() {
        return this.alias;
    }

    /**
     * Method setAlias.
     *
     * @param alias String
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * Method getCurrency.
     *
     * @return String
     */
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Method setCurrency.
     *
     * @param currency String
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Method getAvailableFunds.
     *
     * @return BigDecimal
     */
    public BigDecimal getAvailableFunds() {
        return this.availableFunds;
    }

    /**
     * Method setAvailableFunds.
     *
     * @param availableFunds BigDecimal
     */
    public void setAvailableFunds(BigDecimal availableFunds) {
        this.availableFunds = availableFunds;
    }

    /**
     * Method getBuyingPower.
     *
     * @return BigDecimal
     */
    public BigDecimal getBuyingPower() {
        return this.buyingPower;
    }

    /**
     * Method setBuyingPower.
     *
     * @param buyingPower BigDecimal
     */
    public void setBuyingPower(BigDecimal buyingPower) {
        this.buyingPower = buyingPower;
    }

    /**
     * Method getCashBalance.
     *
     * @return BigDecimal
     */
    public BigDecimal getCashBalance() {
        return this.cashBalance;
    }

    /**
     * Method setCashBalance.
     *
     * @param cashBalance BigDecimal
     */
    public void setCashBalance(BigDecimal cashBalance) {
        this.cashBalance = cashBalance;
    }

    /**
     * Method getGrossPositionValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getGrossPositionValue() {
        return this.grossPositionValue;
    }

    /**
     * Method setGrossPositionValue.
     *
     * @param grossPositionValue BigDecimal
     */
    public void setGrossPositionValue(BigDecimal grossPositionValue) {
        this.grossPositionValue = grossPositionValue;
    }

    /**
     * Method getRealizedPnL.
     *
     * @return BigDecimal
     */
    public BigDecimal getRealizedPnL() {
        return this.realizedPnL;
    }

    /**
     * Method setRealizedPnL.
     *
     * @param realizedPnL BigDecimal
     */
    public void setRealizedPnL(BigDecimal realizedPnL) {
        this.realizedPnL = realizedPnL;
    }

    /**
     * Method getUnrealizedPnL.
     *
     * @return BigDecimal
     */
    public BigDecimal getUnrealizedPnL() {
        return this.unrealizedPnL;
    }

    /**
     * Method setUnrealizedPnL.
     *
     * @param unrealizedPnL BigDecimal
     */
    public void setUnrealizedPnL(BigDecimal unrealizedPnL) {
        this.unrealizedPnL = unrealizedPnL;
    }

    /**
     * Method getDefaultPortfolio.
     *
     * @return Portfolio
     */
    public PortfolioDto getDefaultPortfolio() {

        for (PortfolioDto item : this.portfolios) {

            if (item.getIsDefault()) {

                return item;
            }
        }
        return null;
    }

    /**
     * Method getPortfolios.
     *
     * @return List<PortfolioDto>
     */
    public List<PortfolioDto> getPortfolios() {
        return this.portfolios;
    }

    /**
     * Method setPortfolios.
     *
     * @param portfolios List<PortfolioDto>
     */
    @JsonIgnore
    public void setPortfolios(List<PortfolioDto> portfolios) {
        this.portfolios = portfolios;
    }

    /**
     * Method isDirty.
     *
     * @return boolean
     */
    public boolean isDirty() {

        for (PortfolioDto item : this.getPortfolios()) {

            if (item.isDirty()) {
                return true;
            }
        }
        return super.isDirty();
    }

    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        return super.clone();
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return this.getAccountNumber() + "-" + this.getName();
    }
}
