package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import org.trade.core.dao.Aspect;
import org.trade.core.valuetype.AccountType;
import org.trade.core.valuetype.Currency;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * Account generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
@Entity
@Table(name = "account")
public class Account extends Aspect implements Serializable, Cloneable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 5891080561163346464L;

    @Column(name = "name", unique = true, nullable = false, length = 45)
    private String name;

    @Column(name = "account_number", unique = true, nullable = false, length = 20)
    private String accountNumber;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    @Column(name = "alias", unique = true, length = 45)
    private String alias;

    @Column(name = "account_type", length = 20)
    private String accountType;

    @Column(name = "available_funds", precision = 10)
    private BigDecimal availableFunds = new BigDecimal(0);

    @Column(name = "buying_power", precision = 10)
    private BigDecimal buyingPower = new BigDecimal(0);

    @Column(name = "cash_balance", precision = 10)
    private BigDecimal cashBalance = new BigDecimal(0);

    @Column(name = "gross_position_value", precision = 10)
    private BigDecimal grossPositionValue = new BigDecimal(0);

    @Column(name = "realized_pn_l", precision = 10)
    private BigDecimal realizedPnL = new BigDecimal(0);

    @Column(name = "unrealized_pn_l", precision = 10)
    private BigDecimal unrealizedPnL = new BigDecimal(0);

    @ManyToMany(mappedBy = "accounts")
    private List<Portfolio> portfolios = new ArrayList<>(0);

    @ManyToMany(mappedBy = "accounts")
    private List<User> users = new ArrayList<>(0);

    public Account() {

        this.accountType = AccountType.INDIVIDUAL;
        this.currency = Currency.USD;
    }

    /**
     * Constructor for Account.
     *
     * @param name          String
     * @param accountNumber String
     * @param currency      String
     * @param accountType   String
     */
    public Account(String name, String accountNumber, String currency, String accountType) {

        this.accountNumber = accountNumber;
        this.accountType = accountType;
        this.name = name;
        this.currency = currency;
    }

    /**
     * Constructor for Account.
     *
     * @param accountNumber      String
     * @param name               String
     * @param availableFunds     BigDecimal
     * @param buyingPower        BigDecimal
     * @param cashBalance        BigDecimal
     * @param currency           String
     * @param grossPositionValue BigDecimal
     * @param realizedPnL        BigDecimal
     * @param unrealizedPnL      BigDecimal
     */
    public Account(String accountNumber, String name, String accountType, BigDecimal availableFunds,
                   BigDecimal buyingPower, BigDecimal cashBalance, String currency, BigDecimal grossPositionValue,
                   BigDecimal realizedPnL, BigDecimal unrealizedPnL) {

        this.accountNumber = accountNumber;
        this.accountType = accountType;
        this.name = name;
        this.availableFunds = availableFunds;
        this.buyingPower = buyingPower;
        this.cashBalance = cashBalance;
        this.currency = currency;
        this.grossPositionValue = grossPositionValue;
        this.realizedPnL = realizedPnL;
        this.unrealizedPnL = unrealizedPnL;
    }

    /**
     * Method getName.
     *
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Method setName.
     *
     * @param name String
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Method getAccountNumber.
     *
     * @return String
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Method setAccountNumber.
     *
     * @param accountNumber String
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Method getAccountType.
     *
     * @return String
     */
    public String getAccountType() {
        return this.accountType;
    }

    /**
     * Method setAccountType.
     *
     * @param accountType String
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * Method getAlias.
     *
     * @return String
     */
    public String getAlias() {
        return this.alias;
    }

    /**
     * Method setAlias.
     *
     * @param alias String
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * Method getCurrency.
     *
     * @return String
     */
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Method setCurrency.
     *
     * @param currency String
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Method getAvailableFunds.
     *
     * @return BigDecimal
     */
    public BigDecimal getAvailableFunds() {
        return this.availableFunds;
    }

    /**
     * Method setAvailableFunds.
     *
     * @param availableFunds BigDecimal
     */
    public void setAvailableFunds(BigDecimal availableFunds) {
        this.availableFunds = availableFunds;
    }

    /**
     * Method getBuyingPower.
     *
     * @return BigDecimal
     */
    public BigDecimal getBuyingPower() {
        return this.buyingPower;
    }

    /**
     * Method setBuyingPower.
     *
     * @param buyingPower BigDecimal
     */
    public void setBuyingPower(BigDecimal buyingPower) {
        this.buyingPower = buyingPower;
    }

    /**
     * Method getCashBalance.
     *
     * @return BigDecimal
     */
    public BigDecimal getCashBalance() {
        return this.cashBalance;
    }

    /**
     * Method setCashBalance.
     *
     * @param cashBalance BigDecimal
     */
    public void setCashBalance(BigDecimal cashBalance) {
        this.cashBalance = cashBalance;
    }

    /**
     * Method getGrossPositionValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getGrossPositionValue() {
        return this.grossPositionValue;
    }

    /**
     * Method setGrossPositionValue.
     *
     * @param grossPositionValue BigDecimal
     */
    public void setGrossPositionValue(BigDecimal grossPositionValue) {
        this.grossPositionValue = grossPositionValue;
    }

    /**
     * Method getRealizedPnL.
     *
     * @return BigDecimal
     */
    public BigDecimal getRealizedPnL() {
        return this.realizedPnL;
    }

    /**
     * Method setRealizedPnL.
     *
     * @param realizedPnL BigDecimal
     */
    public void setRealizedPnL(BigDecimal realizedPnL) {
        this.realizedPnL = realizedPnL;
    }

    /**
     * Method getUnrealizedPnL.
     *
     * @return BigDecimal
     */
    public BigDecimal getUnrealizedPnL() {
        return this.unrealizedPnL;
    }

    /**
     * Method setUnrealizedPnL.
     *
     * @param unrealizedPnL BigDecimal
     */
    public void setUnrealizedPnL(BigDecimal unrealizedPnL) {
        this.unrealizedPnL = unrealizedPnL;
    }

    /**
     * Method getDefaultPortfolio.
     *
     * @return Portfolio
     */
    @Transient
    public Portfolio getDefaultPortfolio() {

        for (Portfolio item : this.portfolios) {

            if (item.getIsDefault()) {

                return item;
            }
        }
        return null;
    }

    /**
     * Method getPortfolios.
     *
     * @return List<Portfolio>
     */
    public List<Portfolio> getPortfolios() {
        return this.portfolios;
    }

    /**
     * Method setPortfolios.
     *
     * @param portfolios List<Portfolio>
     */
    public void setPortfolios(List<Portfolio> portfolios) {
        this.portfolios = portfolios;
    }

    /**
     * Method getUsers.
     *
     * @return List<User>
     */
    public List<User> getUsers() {
        return this.users;
    }

    /**
     * Method setUsers.
     *
     * @param users List<User>
     */
    public void setUsers(List<User> users) {
        this.users = users;
    }

    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        return super.clone();
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return this.getAccountNumber() + "-" + this.getName();
    }
}
