/* ===========================================================
 * TradeManager : a application to trade strategies for the Java(tm) platform
 * ===========================================================
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Project Info:  org.trade
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * [Java is a trademark or registered trademark of Oracle, Inc.
 * in the United States and other countries.]
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Original Author:  Simon Allen;
 * Contributor(s):   -;
 *
 * Changes
 * -------
 *
 */
package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.dao.Aspect;

import java.io.Serial;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.ZonedDateTime;


/**
 * Candle generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class CandleDto extends Aspect implements java.io.Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 7644763985378994305L;

    private ZonedDateTime startPeriod;
    private ZonedDateTime endPeriod;
    private BigDecimal open;
    private BigDecimal close;
    private BigDecimal high;
    private BigDecimal low;
    private String period;
    private Integer tradeCount;
    private Long volume;
    private BigDecimal vwap;
    private Integer barSize;
    private ZonedDateTime lastUpdateDate;
    private ContractDto contract;

    public CandleDto() {
    }

    /**
     * Method getContract.
     *
     * @return ContractDto
     */
    public ContractDto getContract() {
        return this.contract;
    }

    /**
     * Method setContract.
     *
     * @param contract ContractDto
     */
    public void setContract(ContractDto contract) {
        this.contract = contract;
    }

    /**
     * Method getClose.
     *
     * @return BigDecimal
     */
    public BigDecimal getClose() {
        return this.close;
    }

    /**
     * Method setClose.
     *
     * @param close BigDecimal
     */
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    /**
     * Method getHigh.
     *
     * @return BigDecimal
     */
    public BigDecimal getHigh() {
        return this.high;
    }

    /**
     * Method setHigh.
     *
     * @param high BigDecimal
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * Method getLow.
     *
     * @return BigDecimal
     */
    public BigDecimal getLow() {
        return this.low;
    }

    /**
     * Method setLow.
     *
     * @param low BigDecimal
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * Method getOpen.
     *
     * @return BigDecimal
     */
    public BigDecimal getOpen() {
        return this.open;
    }

    /**
     * Method setOpen.
     *
     * @param open BigDecimal
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    /**
     * Method getPeriod.
     *
     * @return String
     */
    public String getPeriod() {
        return this.period;
    }

    /**
     * Method setPeriod.
     *
     * @param period String
     */
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * Method getEndPeriod.
     *
     * @return Date
     */
    public ZonedDateTime getEndPeriod() {
        return this.endPeriod;
    }

    /**
     * Method setEndPeriod.
     *
     * @param endPeriod Date
     */
    public void setEndPeriod(ZonedDateTime endPeriod) {
        this.endPeriod = endPeriod;
    }

    /**
     * Method getStartPeriod.
     *
     * @return Date
     */
    public ZonedDateTime getStartPeriod() {
        return this.startPeriod;
    }

    /**
     * Method setStartPeriod.
     *
     * @param startPeriod Date
     */
    public void setStartPeriod(ZonedDateTime startPeriod) {
        this.startPeriod = startPeriod;
    }

    /**
     * Method getTradeCount.
     *
     * @return Integer
     */
    public Integer getTradeCount() {
        return this.tradeCount;
    }

    /**
     * Method setTradeCount.
     *
     * @param tradeCount Integer
     */
    public void setTradeCount(Integer tradeCount) {
        this.tradeCount = tradeCount;
    }

    /**
     * Method getVolume.
     *
     * @return Long
     */
    public Long getVolume() {
        return this.volume;
    }

    /**
     * Method setVolume.
     *
     * @param volume Long
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * Method getVwap.
     *
     * @return BigDecimal
     */
    public BigDecimal getVwap() {
        return this.vwap;
    }

    /**
     * Method setVwap.
     *
     * @param vwap BigDecimal
     */
    public void setVwap(BigDecimal vwap) {
        this.vwap = vwap;
    }

    /**
     * Method getBarSize.
     *
     * @return Integer
     */
    public Integer getBarSize() {

        if (null == this.barSize) {

            Duration duration = Duration.between(getStartPeriod(), getEndPeriod());
            this.barSize = (int) (duration.getSeconds() + 1);
        }
        return this.barSize;
    }

    /**
     * Method setBarSize.
     *
     * @param barSize Integer
     */
    public void setBarSize(Integer barSize) {
        this.barSize = barSize;
    }

    /**
     * Method getLastUpdateDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    /**
     * Method setLastUpdateDate.
     *
     * @param lastUpdateDate ZonedDateTime
     */
    public void setLastUpdateDate(ZonedDateTime lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {

            return true;
        }

        if (objectToCompare instanceof CandleDto candle) {

            if (this.getContract().equals(candle.getContract())) {

                if (this.getStartPeriod().equals(candle.getStartPeriod())) {

                    if (this.getEndPeriod().equals(candle.getEndPeriod())) {

                        if (this.getHigh().setScale(2, RoundingMode.HALF_EVEN).equals(candle.getHigh())) {

                            if (this.getLow().setScale(2, RoundingMode.HALF_EVEN).equals(candle.getLow())) {

                                if (this.getOpen().setScale(2, RoundingMode.HALF_EVEN).equals(candle.getOpen())) {

                                    if (this.getClose().setScale(2, RoundingMode.HALF_EVEN).equals(candle.getClose())) {

                                        return this.getVolume().equals(candle.getVolume());
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
}
