package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.trade.core.dao.Aspect;

import java.io.Serial;
import java.io.Serializable;
import java.time.ZonedDateTime;


/**
 * Contract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */

public class ContractDto extends Aspect implements Serializable, Cloneable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 5691902477608387034L;

    private String symbol;
    private String currency;
    private String exchange;
    private ZonedDateTime expiry;
    private String secType;
    private Integer requestId;
    private TradePositionDto tradePosition;

    public ContractDto() {
    }

    /**
     * Method getRequestId.
     *
     * @return Integer
     */
    public Integer getRequestId() {

        return this.requestId;
    }

    /**
     * Method setRequestId.
     *
     * @param requestId Integer
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * Method getCurrency.
     *
     * @return String
     */
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Method setCurrency.
     *
     * @param currency String
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Method getExchange.
     *
     * @return String
     */
    public String getExchange() {
        return this.exchange;
    }

    /**
     * Method setExchange.
     *
     * @param exchange String
     */
    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    /**
     * Method getExpiry.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getExpiry() {
        return this.expiry;
    }

    /**
     * Method setExpiry.
     *
     * @param expiry ZonedDateTime
     */
    public void setExpiry(ZonedDateTime expiry) {
        this.expiry = expiry;
    }

    /**
     * Method getSymbol.
     *
     * @return String
     */
    public String getSymbol() {
        return this.symbol;
    }

    /**
     * Method setSymbol.
     *
     * @param symbol String
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Method getSecType.
     *
     * @return String
     */
    public String getSecType() {
        return this.secType;
    }

    /**
     * Method setSecType.
     *
     * @param secType String
     */
    public void setSecType(String secType) {
        this.secType = secType;
    }


    /**
     * Method getTradePosition.
     *
     * @return TradePositionDto
     */
    public TradePositionDto getTradePosition() {
        return this.tradePosition;
    }

    /**
     * Method setTradePosition.
     *
     * @param tradePosition TradePositionDto
     */
    @JsonIgnore
    public void setTradePosition(TradePositionDto tradePosition) {
        this.tradePosition = tradePosition;
    }

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {

            return true;
        }

        if (objectToCompare instanceof ContractDto contract) {

            if (this.getSymbol().equals(contract.getSymbol())) {

                if (this.getSecType().equals(contract.getSecType())) {

                    if (this.getExchange().equals(contract.getExchange())) {

                        return this.getCurrency().equals(contract.getCurrency());
                    }
                }
            }
        }
        return false;
    }

    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        ContractDto contract = (ContractDto) super.clone();
        return contract;
    }

    /**
     * Method hashCode.
     * <p>
     * For every field tested in the equals-Method, calculate a hash code c by:
     * <p>
     * If the field f is a boolean: calculate * (f ? 0 : 1);
     * <p>
     * If the field f is a byte, char, short or int: calculate (int)f;
     * <p>
     * If the field f is a long: calculate (int)(f ^ (f >>> 32));
     * <p>
     * If the field f is a float: calculate Float.floatToIntBits(f);
     * <p>
     * If the field f is a double: calculate Double.doubleToLongBits(f) and
     * handle the return value like every long value;
     * <p>
     * If the field f is an object: Use the result of the hashCode() method or 0
     * if f == null;
     * <p>
     * If the field f is an array: See every field as separate element and
     * calculate the hash value in a recursive fashion and combine the values as
     * described next.
     *
     * @return int
     */
    public int hashCode() {

        int hash = super.hashCode();
        hash = hash + this.getCurrency().hashCode();
        hash = hash + this.getExchange().hashCode();
        hash = hash + this.getSecType().hashCode();
        hash = hash + this.getSymbol().hashCode();
        return hash;
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return getSymbol().toUpperCase();
    }
}
