/* ===========================================================
 * TradeManager : a application to trade strategies for the Java(tm) platform
 * ===========================================================
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Project Info:  org.trade
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * [Java is a trademark or registered trademark of Oracle, Inc.
 * in the United States and other countries.]
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Original Author:  Simon Allen;
 * Contributor(s):   -;
 *
 * Changes
 * -------
 *
 */
package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.dao.Aspect;
import org.trade.core.util.CoreUtils;
import org.trade.core.valuetype.ContentType;

import java.io.Serial;
import java.io.Serializable;
import java.util.Comparator;
import java.util.Objects;


/**
 * Rule generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class RuleDto extends Aspect implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 2273276207080568947L;

    private String comment;
    private byte[] rule;
    protected Integer ruleVersion;
    private String contentType = ContentType.JAVA;
    private StrategyDto strategy;

    public RuleDto() {

    }

    /**
     * Constructor for Rule.
     *
     * @param strategy    StrategyDto
     * @param ruleVersion Integer
     * @param comment     String
     */
    public RuleDto(StrategyDto strategy, Integer ruleVersion, String comment) {

        this.strategy = strategy;
        this.ruleVersion = ruleVersion;
        this.comment = comment;
    }

    /**
     * Constructor for Rule.
     *
     * @param strategy    StrategyDto
     * @param ruleVersion Integer
     * @param comment     String
     * @param rule        byte[]
     * @param contentType String
     */
    public RuleDto(StrategyDto strategy, Integer ruleVersion, String comment, byte[] rule, String contentType) {

        this.strategy = strategy;
        this.ruleVersion = ruleVersion;
        this.comment = comment;
        this.rule = rule;
        this.contentType = contentType;
    }

    /**
     * Method getStrategy.
     *
     * @return StrategyDto
     */
    public StrategyDto getStrategy() {
        return this.strategy;
    }

    /**
     * Method setStrategy.
     *
     * @param strategy StrategyDto
     */
    public void setStrategy(StrategyDto strategy) {
        this.strategy = strategy;
    }

    /**
     * Method getComment.
     *
     * @return String
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Method setComment.
     *
     * @param comment String
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Method getRule.
     *
     * @return byte[]
     */
    public byte[] getRule() {
        return this.rule;
    }

    /**
     * Method setRule.
     *
     * @param rule byte[]
     */
    public void setRule(byte[] rule) {
        this.rule = rule;
    }

    /**
     * Method getRuleVersion.
     *
     * @return Integer
     */
    public Integer getRuleVersion() {
        return this.ruleVersion;
    }

    /**
     * Method getRuleVersion.
     *
     * @param ruleVersion Integer
     */
    public void setRuleVersion(Integer ruleVersion) {
        this.ruleVersion = ruleVersion;
    }

    /**
     * Method getContentType.
     *
     * @return String
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Method setContentType.
     *
     * @param contentType String
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return "Version-" + this.getRuleVersion();
    }

    public static final Comparator<RuleDto> VERSION_ORDER = (o1, o2) -> CoreUtils.nullSafeComparator(o1.getRuleVersion(), o2.getRuleVersion());

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {
            return true;
        }

        if (objectToCompare instanceof RuleDto) {

            if (null == this.getId() || null == this.getRuleVersion()) {

                return false;
            }

            return Objects.equals(this.getStrategy().getId(), ((RuleDto) objectToCompare).getStrategy().getId())
                    && this.getRuleVersion().equals(((RuleDto) objectToCompare).getRuleVersion());

        }
        return false;
    }
}
