package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.dao.Aspect;
import org.trade.core.util.CoreUtils;
import org.trade.core.valuetype.ContentType;

import java.io.Serial;
import java.io.Serializable;
import java.util.Comparator;
import java.util.Objects;


/**
 * Rule generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class RuleDTO extends Aspect implements Serializable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 2273276207080568947L;

    private String comment;
    private byte[] rule;
    protected Integer ruleVersion;
    private String contentType = ContentType.JAVA;
    private StrategyDTO strategy;

    public RuleDTO() {

    }

    /**
     * Constructor for Rule.
     *
     * @param strategy    StrategyDto
     * @param ruleVersion Integer
     * @param comment     String
     */
    public RuleDTO(StrategyDTO strategy, Integer ruleVersion, String comment) {

        this.strategy = strategy;
        this.ruleVersion = ruleVersion;
        this.comment = comment;
    }

    /**
     * Constructor for Rule.
     *
     * @param strategy    StrategyDto
     * @param ruleVersion Integer
     * @param comment     String
     * @param rule        byte[]
     * @param contentType String
     */
    public RuleDTO(StrategyDTO strategy, Integer ruleVersion, String comment, byte[] rule, String contentType) {

        this.strategy = strategy;
        this.ruleVersion = ruleVersion;
        this.comment = comment;
        this.rule = rule;
        this.contentType = contentType;
    }

    /**
     * Method getStrategy.
     *
     * @return StrategyDto
     */
    public StrategyDTO getStrategy() {
        return this.strategy;
    }

    /**
     * Method setStrategy.
     *
     * @param strategy StrategyDto
     */
    public void setStrategy(StrategyDTO strategy) {
        this.strategy = strategy;
    }

    /**
     * Method getComment.
     *
     * @return String
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Method setComment.
     *
     * @param comment String
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Method getRule.
     *
     * @return byte[]
     */
    public byte[] getRule() {
        return this.rule;
    }

    /**
     * Method setRule.
     *
     * @param rule byte[]
     */
    public void setRule(byte[] rule) {
        this.rule = rule;
    }

    /**
     * Method getRuleVersion.
     *
     * @return Integer
     */
    public Integer getRuleVersion() {
        return this.ruleVersion;
    }

    /**
     * Method getRuleVersion.
     *
     * @param ruleVersion Integer
     */
    public void setRuleVersion(Integer ruleVersion) {
        this.ruleVersion = ruleVersion;
    }

    /**
     * Method getContentType.
     *
     * @return String
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Method setContentType.
     *
     * @param contentType String
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return "Version-" + this.getRuleVersion();
    }

    public static final Comparator<RuleDTO> VERSION_ORDER = (o1, o2) -> CoreUtils.nullSafeComparator(o1.getRuleVersion(), o2.getRuleVersion());

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {
            return true;
        }

        if (objectToCompare instanceof RuleDTO) {

            if (null == this.getId() || null == this.getRuleVersion()) {

                return false;
            }

            return Objects.equals(this.getStrategy().getId(), ((RuleDTO) objectToCompare).getStrategy().getId())
                    && this.getRuleVersion().equals(((RuleDTO) objectToCompare).getRuleVersion());

        }
        return false;
    }
}
