package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.dao.Aspect;

import java.io.Serial;
import java.io.Serializable;


/**
 * Strategy generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class StrategyDto extends Aspect implements Serializable, Cloneable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = -5704206226348654910L;

    private String name;
    private String className;
    private String description;
    private Boolean marketData = false;
    private StrategyDto strategy;

    public StrategyDto() {
    }

    /**
     * Constructor for Strategy.
     *
     * @param name String
     */
    public StrategyDto(String name) {

        this.name = name;
        this.className = name;
    }

    /**
     * Constructor for Strategy.
     *
     * @param name      String
     * @param className String
     */
    public StrategyDto(String name, String className) {

        this.name = name;
        this.className = className;
    }

    /**
     * Constructor for Strategy.
     *
     * @param name        String
     * @param description String
     * @param marketData  Boolean
     * @param className   String
     */
    public StrategyDto(String name, String description, Boolean marketData, String className) {

        this.name = name;
        this.description = description;
        this.marketData = marketData;
        this.className = className;
    }

    /**
     * Method getName.
     *
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Method setName.
     *
     * @param name String
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Method getClassName.
     *
     * @return String
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Method setClassName.
     *
     * @param className String
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Method getDescription.
     *
     * @return String
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Method setDescription.
     *
     * @param description String
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Method getMarketData.
     *
     * @return Boolean
     */
    public Boolean getMarketData() {
        return this.marketData;
    }

    /**
     * Method setMarketData.
     *
     * @param marketData Boolean
     */
    public void setMarketData(Boolean marketData) {
        this.marketData = marketData;
    }


    /**
     * Method getStrategyManager.
     *
     * @return Strategy
     */
    public StrategyDto getStrategyManager() {
        return this.strategy;
    }

    /**
     * Method setStrategyManager.
     *
     * @param strategy Strategy
     */
    public void setStrategyManager(StrategyDto strategy) {
        this.strategy = strategy;
    }

    /**
     * Method getStrategyManager.
     *
     * @return boolean
     */
    public boolean hasStrategyManager() {
        return null != getStrategyManager();
    }


    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        StrategyDto strategy = (StrategyDto) super.clone();
        return strategy;
    }

    /**
     * Method hashCode.
     * <p>
     * For every field tested in the equals-Method, calculate a hash code c by:
     * <p>
     * If the field f is a boolean: calculate * (f ? 0 : 1); If the field f is a
     * byte, char, short or int: calculate (int)f;
     * <p>
     * If the field f is a long: calculate (int)(f ^ (f >>> 32));
     * <p>
     * If the field f is a float: calculate Float.floatToIntBits(f);
     * <p>
     * If the field f is a double: calculate Double.doubleToLongBits(f) and
     * handle the return value like every long value;
     * <p>
     * If the field f is an object: Use the result of the hashCode() method or 0
     * if f == null;
     * <p>
     * If the field f is an array: See every field as separate element and
     * calculate the hash value in a recursive fashion and combine the values as
     * described next.
     *
     * @return int
     */
    public int hashCode() {
        int hash = super.hashCode();
        hash = hash + (this.getName() == null ? 0 : this.getName().hashCode());
        hash = hash + (this.getClassName() == null ? 0 : this.getClassName().hashCode());
        return hash;
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return this.getName();
    }

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {
        return super.equals(objectToCompare);
    }
}
