/* ===========================================================
 * TradeManager : a application to trade strategies for the Java(tm) platform
 * ===========================================================
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Project Info:  org.trade
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * [Java is a trademark or registered trademark of Oracle, Inc.
 * in the United States and other countries.]
 *
 * (C) Copyright 2011-2011, by Simon Allen and Contributors.
 *
 * Original Author:  Simon Allen;
 * Contributor(s):   -;
 *
 * Changes
 * -------
 *
 */
package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import org.trade.core.dao.Aspect;
import org.trade.core.valuetype.Money;

import java.io.Serial;
import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Trade generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class TradePositionDto extends Aspect implements java.io.Serializable {

    /**
     * There can only ever be one TradePosition open at a time for a Contract. A
     * TradePosition is created when at least one TradeOrder becomes
     * filled/partially filled.
     * <p>
     * The TradeOrder that caused the TradePosition to be created is marked as
     * the opening TradeOrder.
     * <p>
     * A TradePosition is closed when the total open quantity i.e. buy quantity
     * less sell quantity equals zero. At this point the net value represents
     * the P/L for the position.
     */

    @Serial
    private static final long serialVersionUID = 715993951200025530L;

    private ZonedDateTime openDate;
    private String side;
    private Integer openQuantity = 0;
    private ZonedDateTime closeDate;
    private BigDecimal totalCommission;
    private Integer totalBuyQuantity;
    private BigDecimal totalBuyValue;
    private Integer totalSellQuantity;
    private BigDecimal totalSellValue;
    private BigDecimal totalNetValue;
    private ContractDto contract;
    private List<TradeOrderDto> tradeOrders = new ArrayList<>(0);

    public TradePositionDto() {
    }

    /**
     * Constructor for TradePosition.
     *
     * @param contract         ContractDto
     * @param positionOpenDate Date
     * @param side             String
     */
    public TradePositionDto(ContractDto contract, ZonedDateTime positionOpenDate, String side) {

        this.contract = contract;
        this.openDate = positionOpenDate;
        this.side = side;
    }

    /**
     * Constructor for TradePosition.
     *
     * @param contract          ContractDto
     * @param positionOpenDate  ZonedDateTime
     * @param positionCloseDate ZonedDateTime
     * @param openQuantity      Integer
     * @param side              String
     * @param totalBuyQuantity  Integer
     * @param totalBuyValue     BigDecimal
     * @param totalSellQuantity Integer
     * @param totalSellValue    BigDecimal
     * @param totalNetValue     BigDecimal
     * @param tradeOrders       List<TradeOrder>
     */
    public TradePositionDto(ContractDto contract, ZonedDateTime positionOpenDate, ZonedDateTime positionCloseDate,
                            Integer openQuantity, String side, BigDecimal totalCommission, Integer totalBuyQuantity,
                            BigDecimal totalBuyValue, Integer totalSellQuantity, BigDecimal totalSellValue, BigDecimal totalNetValue,
                            List<TradeOrderDto> tradeOrders) {

        this.contract = contract;
        this.openDate = positionOpenDate;
        this.closeDate = positionCloseDate;
        this.openQuantity = openQuantity;
        this.side = side;
        this.totalCommission = totalCommission;
        this.totalBuyQuantity = totalBuyQuantity;
        this.totalBuyValue = totalBuyValue;
        this.totalSellQuantity = totalSellQuantity;
        this.totalSellValue = totalSellValue;
        this.totalNetValue = totalNetValue;
        this.tradeOrders = tradeOrders;
    }

    /**
     * Method getContract.
     *
     * @return ContractDto
     */
    public ContractDto getContract() {
        return this.contract;
    }

    /**
     * Method setContract.
     *
     * @param contract ContractDto
     */
    public void setContract(ContractDto contract) {
        this.contract = contract;
    }

    /**
     * Method getPositionOpenDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOpenDate() {
        return this.openDate;
    }

    /**
     * Method setPositionOpenDate.
     *
     * @param openDate ZonedDateTime
     */
    public void setOpenDate(ZonedDateTime openDate) {
        this.openDate = openDate;
    }

    /**
     * Method getPositionCloseDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCloseDate() {
        return this.closeDate;
    }

    /**
     * Method setPositionCloseDate.
     *
     * @param closeDate ZonedDateTime
     */
    public void setCloseDate(ZonedDateTime closeDate) {
        this.closeDate = closeDate;
    }

    /**
     * Method getOpenQuantity.
     *
     * @return Integer
     */
    public Integer getOpenQuantity() {
        return this.openQuantity;
    }

    /**
     * Method setOpenQuantity.
     *
     * @param openQuantity Integer
     */
    public void setOpenQuantity(Integer openQuantity) {
        this.openQuantity = openQuantity;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }

    /**
     * Method setSide.
     *
     * @param side String
     */
    public void setSide(String side) {
        this.side = side;
    }

    /**
     * Method getTotalCommission.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalCommission() {
        return this.totalCommission;
    }

    /**
     * Method setTotalCommission.
     *
     * @param totalCommission BigDecimal
     */
    public void setTotalCommission(BigDecimal totalCommission) {
        this.totalCommission = totalCommission;
    }

    /**
     * Method getTotalBuyQuantity.
     *
     * @return Integer
     */
    public Integer getTotalBuyQuantity() {
        return this.totalBuyQuantity;
    }

    /**
     * Method setTotalBuyQuantity.
     *
     * @param totalBuyQuantity Integer
     */
    public void setTotalBuyQuantity(Integer totalBuyQuantity) {
        this.totalBuyQuantity = totalBuyQuantity;
    }

    /**
     * Method getTotalSellQuantity.
     *
     * @return Integer
     */
    public Integer getTotalSellQuantity() {
        return this.totalSellQuantity;
    }

    /**
     * Method setTotalSellQuantity.
     *
     * @param totalSellQuantity Integer
     */
    public void setTotalSellQuantity(Integer totalSellQuantity) {
        this.totalSellQuantity = totalSellQuantity;
    }

    /**
     * Method getTotalBuyValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalBuyValue() {
        return this.totalBuyValue;
    }

    /**
     * Method setTotalBuyValue.
     *
     * @param totalBuyValue BigDecimal
     */
    public void setTotalBuyValue(BigDecimal totalBuyValue) {
        this.totalBuyValue = totalBuyValue;
    }

    /**
     * Method getTotalSellValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalSellValue() {
        return this.totalSellValue;
    }

    /**
     * Method setTotalSellValue.
     *
     * @param totalSellValue BigDecimal
     */
    public void setTotalSellValue(BigDecimal totalSellValue) {
        this.totalSellValue = totalSellValue;
    }

    /**
     * Method getTotalNetValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalNetValue() {
        return this.totalNetValue;
    }

    /**
     * Method setTotalNetValue.
     *
     * @param totalNetValue BigDecimal
     */
    public void setTotalNetValue(BigDecimal totalNetValue) {
        this.totalNetValue = totalNetValue;
    }

    /**
     * Method getTradeOrders.
     *
     * @return List<TradeOrderDto>
     */
    public List<TradeOrderDto> getTradeOrders() {
        return this.tradeOrders;
    }

    /**
     * Method setTradeOrders.
     *
     * @param tradeOrders List<TradeOrderDto>
     */
    public void setTradeOrders(List<TradeOrderDto> tradeOrders) {
        this.tradeOrders = tradeOrders;
    }

    /**
     * Method addTradeOrder.
     *
     * @param tradeOrders TradeOrderDto
     */
    public void addTradeOrder(TradeOrderDto tradeOrders) {
        this.tradeOrders.add(tradeOrders);
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {

        return "TradePosition Id: " + this.getId() + " Version: " + this.getVersion()
                + " positionOpenDate: " + this.getOpenDate() + " positionCloseDate: "
                + this.getCloseDate() + " Side: " + this.getSide() + " Open Qty: " + this.getOpenQuantity()
                + " Total Buy qty: " + this.getTotalBuyQuantity() + " Total Buy Value: "
                + new Money(this.getTotalBuyValue()) + " Total Sell qty: " + this.getTotalSellQuantity()
                + " Total Sell Value: " + new Money(this.getTotalSellValue()) + " Total Comm: "
                + new Money(this.getTotalCommission()) + " updateDate: " + this.getUpdateDate();
    }
}
