package org.trade.core.persistent.dao;

import jakarta.persistence.PrePersist;
import org.trade.core.dao.Aspect;
import org.trade.core.util.CoreUtils;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Tradestrategy generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class TradestrategyDto extends Aspect implements Serializable, Cloneable {

    @Serial
    private static final long serialVersionUID = -2181676329258092177L;

    private BigDecimal riskAmount;
    private Integer chartDays;
    private Integer barSize;
    private String tier;
    private String status;
    private String side;
    private Boolean trade = false;
    private Integer requestId;
    private StrategyDto strategy;
    private PortfolioDto portfolio;
    private ContractDto contract;
    private TradingdayDto tradingday;
    private List<TradeOrderDto> tradeOrders = new ArrayList<>(0);


    public TradestrategyDto() {
    }

    @PrePersist
    public void initializeRequestId() {

        getRequestId();
    }

    /**
     * Constructor for Tradestrategy.
     *
     * @param chartDays Integer
     * @param barSize   Integer
     * @param strategy  StrategyDto
     */
    public TradestrategyDto(Integer barSize, Integer chartDays, StrategyDto strategy) {

        this.setBarSize(barSize);
        this.chartDays = chartDays;
        this.strategy = strategy;
        super.setDirty(true);
    }

    /**
     * Constructor for Tradestrategy.
     *
     * @param contract ContractDto
     */
    public TradestrategyDto(ContractDto contract) {

        this.contract = contract;
        super.setDirty(true);
    }

    /**
     * Constructor for Tradestrategy.
     *
     * @param contract   ContractDto
     * @param tradingday TradingdayDto
     * @param strategy   StrategyDto
     * @param portfolio  PortfolioDto
     * @param riskAmount BigDecimal
     * @param side       String
     * @param tier       String
     * @param trade      Boolean
     * @param chartDays  Integer
     * @param barSize    Integer
     */
    public TradestrategyDto(ContractDto contract, TradingdayDto tradingday, StrategyDto strategy, PortfolioDto portfolio,
                            BigDecimal riskAmount, String side, String tier, Boolean trade, Integer chartDays, Integer barSize) {

        this.setBarSize(barSize);
        this.chartDays = chartDays;
        this.contract = contract;
        this.strategy = strategy;
        this.tradingday = tradingday;
        this.portfolio = portfolio;
        this.riskAmount = riskAmount;
        this.side = side;
        this.tier = tier;
        this.trade = trade;
        super.setDirty(true);
    }

    /**
     * Method getRequestId.
     *
     * @return Integer
     */
    public Integer getRequestId() {

        return this.requestId;
    }

    /**
     * Method setRequestId.
     *
     * @param requestId Integer
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * Method getBarSize.
     *
     * @return Integer
     */
    public Integer getBarSize() {
        return this.barSize;
    }

    /**
     * Method setBarSize.
     *
     * @param barSize Integer
     */
    public void setBarSize(Integer barSize) {

        this.barSize = barSize;

        if (barSize == 1) {

            Duration duration = Duration.between(this.getTradingday().getOpen(), this.getTradingday().getClose());
            long daySeconds = duration.getSeconds();
            this.barSize = ((int) daySeconds) * barSize;
        }
    }

    /**
     * Method getChartDays.
     *
     * @return Integer
     */
    public Integer getChartDays() {
        return this.chartDays;
    }

    /**
     * Method setChartDays.
     *
     * @param chartDays Integer
     */
    public void setChartDays(Integer chartDays) {
        this.chartDays = chartDays;
    }

    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method setStatus.
     *
     * @param status String
     */
    public void setStatus(String status) {

        this.status = status;
    }

    /**
     * Method getRiskAmount.
     *
     * @return BigDecimal
     */
    public BigDecimal getRiskAmount() {
        return this.riskAmount;
    }

    /**
     * Method setRiskAmount.
     *
     * @param riskAmount BigDecimal
     */
    public void setRiskAmount(BigDecimal riskAmount) {
        this.riskAmount = riskAmount;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }

    /**
     * Method setSide.
     *
     * @param side String
     */
    public void setSide(String side) {
        this.side = side;
    }

    /**
     * Method getTier.
     *
     * @return String
     */
    public String getTier() {
        return this.tier;
    }

    /**
     * Method setTier.
     *
     * @param tier String
     */
    public void setTier(String tier) {
        this.tier = tier;
    }

    /**
     * Method getContract.
     *
     * @return ContractDto
     */
    public ContractDto getContract() {
        return this.contract;
    }

    /**
     * Method setContract.
     *
     * @param contract ContractDto
     */
    public void setContract(ContractDto contract) {
        this.contract = contract;
    }

    /**
     * Method getTradingday.
     *
     * @return TradingdayDto
     */
    public TradingdayDto getTradingday() {
        return this.tradingday;
    }

    /**
     * Method setTradingday.
     *
     * @param tradingday TradingdayDto
     */
    public void setTradingday(TradingdayDto tradingday) {
        this.tradingday = tradingday;
    }

    /**
     * Method getStrategy.
     *
     * @return StrategyDto
     */
    public StrategyDto getStrategy() {
        return this.strategy;
    }

    /**
     * Method setStrategy.
     *
     * @param strategy StrategyDto
     */
    public void setStrategy(StrategyDto strategy) {
        this.strategy = strategy;
    }

    /**
     * Method getPortfolio.
     *
     * @return PortfolioDto
     */
    public PortfolioDto getPortfolio() {
        return this.portfolio;
    }

    /**
     * Method setPortfolio.
     *
     * @param portfolio PortfolioDto
     */
    public void setPortfolio(PortfolioDto portfolio) {
        this.portfolio = portfolio;
    }

    /**
     * Method getTrade.
     *
     * @return Boolean
     */
    public Boolean getTrade() {

        return this.trade;
    }

    /**
     * Method setTrade.
     *
     * @param trade Boolean
     */
    public void setTrade(Boolean trade) {
        this.trade = trade;
    }

    /**
     * Method getTradeOrders.
     *
     * @return List<TradeOrderDto>
     */
    public List<TradeOrderDto> getTradeOrders() {
        return this.tradeOrders;
    }

    /**
     * Method setTradeOrders.
     *
     * @param tradeOrders List<TradeOrderDto>
     */
    public void setTradeOrders(List<TradeOrderDto> tradeOrders) {
        this.tradeOrders = tradeOrders;
    }

    /**
     * Method addTradeOrder.
     *
     * @param tradeOrder TradeOrderDto
     */
    public void addTradeOrder(TradeOrderDto tradeOrder) {

        int index = 0;

        for (TradeOrderDto currTradeOrder : this.tradeOrders) {

            if (CoreUtils.nullSafeComparator(currTradeOrder.getId(), tradeOrder.getId()) == 0) {

                index = this.tradeOrders.indexOf(currTradeOrder);
                break;
            }
        }

        if (index > 0) {

            this.tradeOrders.remove(index);
        }
        this.tradeOrders.add(tradeOrder);
    }


    public static final Comparator<TradestrategyDto> DATE_ORDER_ASC = (o1, o2) -> {

        setAscending(true);
        int returnVal;

        if (CoreUtils.nullSafeComparator(o1.getTradingday().getOpen(), o2.getTradingday().getOpen()) == 0) {

            if (CoreUtils.nullSafeComparator(o1.getSide(), o2.getSide()) == 0) {

                returnVal = CoreUtils.nullSafeComparator(o1.getTier(), o2.getTier());
            } else {

                returnVal = CoreUtils.nullSafeComparator(o1.getSide(), o2.getSide());
            }

        } else {

            returnVal = CoreUtils.nullSafeComparator(o1.getTradingday().getOpen(), o2.getTradingday().getOpen());
        }

        if (getAscending().equals(Boolean.FALSE)) {

            returnVal = returnVal * -1;
        }
        return returnVal;
    };

    public static final Comparator<TradestrategyDto> TRADINGDAY_CONTRACT = (o1, o2) -> {

        setAscending(true);
        int returnVal;

        if (CoreUtils.nullSafeComparator(o1.getTradingday().getOpen(), o2.getTradingday().getOpen()) == 0) {

            if (o1.getContract().equals(o2.getContract())) {

                if (CoreUtils.nullSafeComparator(o1.getBarSize(), o2.getBarSize()) == 0) {

                    returnVal = CoreUtils.nullSafeComparator(o1.getChartDays(), o2.getChartDays());
                } else {

                    returnVal = CoreUtils.nullSafeComparator(o1.getBarSize(), o2.getBarSize());
                }
            } else {

                returnVal = o1.getContract().getSymbol().compareTo(o2.getContract().getSymbol());
            }

        } else {

            returnVal = CoreUtils.nullSafeComparator(o1.getTradingday().getOpen(), o2.getTradingday().getOpen());
        }

        if (getAscending().equals(Boolean.FALSE)) {

            returnVal = returnVal * -1;
        }
        return returnVal;
    };

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {

        return this.getContract().getSymbol().toUpperCase();
    }

    /**
     * Method hashCode.
     * <p>
     * For every field tested in the equals-Method, calculate a hash code c by:
     * <p>
     * If the field f is a boolean: calculate * (f ? 0 : 1);
     * <p>
     * If the field f is a byte, char, short or int: calculate (int)f;
     * <p>
     * If the field f is a long: calculate (int)(f ^ (f >>> 32));
     * <p>
     * If the field f is a float: calculate Float.floatToIntBits(f);
     * <p>
     * If the field f is a double: calculate Double.doubleToLongBits(f) and
     * handle the return value like every long value;
     * <p>
     * If the field f is an object: Use the result of the hashCode() method or 0
     * if f == null;
     * <p>
     * If the field f is an array: See every field as separate element and
     * calculate the hash value in a recursive fashion and combine the values as
     * described next.
     *
     * @return int
     */
    public int hashCode() {

        int hash = super.hashCode();
        hash = hash + this.getContract().hashCode();
        hash = hash + this.getStrategy().hashCode();
        hash = hash + this.getPortfolio().hashCode();
        hash = hash + this.getTradingday().hashCode();
        hash = hash + this.getBarSize().hashCode();
        hash = hash + this.getChartDays().hashCode();
        return hash;
    }

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {
            return true;
        }

        if (objectToCompare instanceof TradestrategyDto tradestrategy) {

            if (this.getContract().equals(tradestrategy.getContract())) {

                if (this.getTradingday().getOpen().compareTo(tradestrategy.getTradingday().getOpen()) == 0) {

                    if (this.getStrategy().getName().equals(tradestrategy.getStrategy().getName())) {

                        if (this.getPortfolio().getName().equals(tradestrategy.getPortfolio().getName())) {

                            return this.getBarSize().equals(tradestrategy.getBarSize());
                        }
                    }
                }
            }
        }
        return false;
    }

    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        TradestrategyDto tradestrategy = (TradestrategyDto) super.clone();
        ContractDto contract = (ContractDto) this.getContract().clone();
        tradestrategy.setContract(contract);
        TradingdayDto tradingday = (TradingdayDto) this.getTradingday().clone();
        tradestrategy.setTradingday(tradingday);
        PortfolioDto portfolio = (PortfolioDto) this.getPortfolio().clone();
        tradestrategy.setPortfolio(portfolio);
        StrategyDto strategy = (StrategyDto) this.getStrategy().clone();
        tradestrategy.setStrategy(strategy);
        List<TradeOrderDto> tradeOrders = new ArrayList<>(0);
        tradestrategy.setTradeOrders(tradeOrders);
        return tradestrategy;
    }
}
