package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 2:18:03 PM by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.Transient;
import org.trade.core.dao.Aspect;
import org.trade.core.util.CoreUtils;
import org.trade.core.util.time.TradingCalendar;

import java.io.Serial;
import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Comparator;


/**
 * Tradingday generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class TradingdayDto extends Aspect implements Serializable, Cloneable {

    /**
     *
     */
    @Serial
    private static final long serialVersionUID = 3388042483785305102L;

    private ZonedDateTime open;
    private ZonedDateTime close;
    private String marketBias;
    private String marketGap;
    private String marketBar;
    private Integer requestId;

    public TradingdayDto() {
    }

    /**
     * Constructor for Tradingday.
     *
     * @param open  ZonedDateTime
     * @param close ZonedDateTime
     */
    public TradingdayDto(ZonedDateTime open, ZonedDateTime close) {

        this.open = open;
        this.close = close;
    }

    /**
     * Constructor for Tradingday.
     *
     * @param open            ZonedDateTime
     * @param close           ZonedDateTime
     * @param marketBias      String
     * @param marketGap       String
     * @param marketBar       String
     * @param tradestrategies List<TradestrategyDto>
     */
    public TradingdayDto(ZonedDateTime open, ZonedDateTime close, String marketBias, String marketGap, String marketBar) {

        this.open = open;
        this.close = close;
        this.marketBias = marketBias;
        this.marketGap = marketGap;
        this.marketBar = marketBar;

    }

    /**
     * Method getRequestId.
     *
     * @return Integer
     */
    public Integer getRequestId() {

        return this.requestId;
    }

    /**
     * Method setRequestId.
     *
     * @param requestId Integer
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * Method getOpen.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOpen() {
        return this.open;
    }

    /**
     * Method setOpen.
     *
     * @param open ZonedDateTime
     */
    public void setOpen(ZonedDateTime open) {
        this.open = open;
    }

    /**
     * Method getClose.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getClose() {
        return this.close;
    }

    /**
     * Method setClose.
     *
     * @param close ZonedDateTime
     */
    public void setClose(ZonedDateTime close) {
        this.close = close;
    }

    /**
     * Method getMarketBias.
     *
     * @return String
     */
    public String getMarketBias() {
        return this.marketBias;
    }

    /**
     * Method setMarketBias.
     *
     * @param marketBias String
     */
    public void setMarketBias(String marketBias) {
        this.marketBias = marketBias;
    }

    /**
     * Method getMarketGap.
     *
     * @return String
     */
    public String getMarketGap() {
        return this.marketGap;
    }

    /**
     * Method setMarketGap.
     *
     * @param marketGap String
     */
    public void setMarketGap(String marketGap) {
        this.marketGap = marketGap;
    }

    /**
     * Method getMarketBar.
     *
     * @return String
     */
    public String getMarketBar() {
        return this.marketBar;
    }

    /**
     * Method setMarketBar.
     *
     * @param marketBar String
     */
    public void setMarketBar(String marketBar) {
        this.marketBar = marketBar;
    }


    public static final Comparator<TradingdayDto> DATE_ORDER_ASC = (o1, o2) -> {

        int returnVal;
        setAscending(true);
        returnVal = CoreUtils.nullSafeComparator(o1.getOpen(), o2.getOpen());

        if (getAscending().equals(Boolean.FALSE)) {

            returnVal = returnVal * -1;
        }
        return returnVal;
    };

    public static final Comparator<TradingdayDto> DATE_ORDER_DESC = (o1, o2) -> {

        int returnVal;
        setAscending(true);
        returnVal = CoreUtils.nullSafeComparator(o1.getOpen(), o2.getOpen());

        if (getAscending().equals(Boolean.FALSE)) {

            returnVal = returnVal * -1;
        }
        return returnVal;
    };

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {
        return TradingCalendar.getFormattedDate(getOpen().toLocalDate(), "MM/dd/yyyy");
    }

    /**
     * Method hashCode.
     * <p>
     * For every field tested in the equals-Method, calculate a hash code c by:
     * <p>
     * If the field f is a boolean: calculate * (f ? 0 : 1);
     * <p>
     * If the field f is a byte, char, short or int: calculate (int)f;
     * <p>
     * If the field f is a long: calculate (int)(f ^ (f >>> 32));
     * <p>
     * If the field f is a float: calculate Float.floatToIntBits(f);
     * <p>
     * If the field f is a double: calculate Double.doubleToLongBits(f) and
     * handle the return value like every long value;
     * <p>
     * If the field f is an object: Use the result of the hashCode() method or 0
     * if f == null;
     * <p>
     * If the field f is an array: See every field as separate element and
     * calculate the hash value in a recursive fashion and combine the values as
     * described next.
     *
     * @return int
     */
    public int hashCode() {

        int hash = super.hashCode();
        hash = hash + (this.getOpen() == null ? 0 : this.getOpen().hashCode());
        hash = hash + (this.getClose() == null ? 0 : this.getClose().hashCode());
        return hash;
    }

    /**
     * Method equals.
     *
     * @param objectToCompare Object
     * @return boolean
     */
    public boolean equals(Object objectToCompare) {

        if (super.equals(objectToCompare)) {

            return true;
        }

        if (objectToCompare instanceof TradingdayDto tradingday) {

            if (tradingday.getOpen().compareTo(this.getOpen()) == 0) {

                return tradingday.getClose().compareTo(this.getClose()) == 0;
            }
        }
        return false;
    }

    /**
     * Method newInstance.
     *
     * @param date ZonedDateTime
     * @return Tradingday
     */
    public static TradingdayDto newInstance(ZonedDateTime date) {

        return new TradingdayDto(TradingCalendar.getTradingDayStart(date),
                TradingCalendar.getTradingDayEnd(date));

    }

    /**
     * Method isDirty.
     *
     * @return boolean
     */
    @Transient
    public boolean isDirty() {

        return super.isDirty();
    }

    /**
     * Method clone.
     *
     * @return Object
     */
    public Object clone() throws CloneNotSupportedException {

        TradingdayDto tradingday = (TradingdayDto) super.clone();
        return tradingday;
    }
}
