package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.trade.core.dao.Aspect;
import org.trade.core.valuetype.Money;

import java.io.Serial;
import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Trade generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class TradePositionDTO extends Aspect implements java.io.Serializable {

    /**
     * There can only ever be one TradePosition open at a time for a Contract. A
     * TradePosition is created when at least one TradeOrder becomes
     * filled/partially filled.
     * <p>
     * The TradeOrder that caused the TradePosition to be created is marked as
     * the opening TradeOrder.
     * <p>
     * A TradePosition is closed when the total open quantity i.e. buy quantity
     * less sell quantity equals zero. At this point the net value represents
     * the P/L for the position.
     */

    @Serial
    private static final long serialVersionUID = 715993951200025530L;

    private ZonedDateTime openDate;
    private String side;
    private Integer openQuantity = 0;
    private ZonedDateTime closeDate;
    private BigDecimal totalCommission;
    private Integer totalBuyQuantity;
    private BigDecimal totalBuyValue;
    private Integer totalSellQuantity;
    private BigDecimal totalSellValue;
    private BigDecimal totalNetValue;
    private ContractDTO contract;
    private List<TradeOrderDTO> tradeOrderDTOs = new ArrayList<>(0);

    public TradePositionDTO() {
    }

    /**
     * Constructor for TradePosition.
     *
     * @param contract         ContractDto
     * @param positionOpenDate Date
     * @param side             String
     */
    public TradePositionDTO(ContractDTO contract, ZonedDateTime positionOpenDate, String side) {

        this.contract = contract;
        this.openDate = positionOpenDate;
        this.side = side;
    }

    /**
     * Constructor for TradePosition.
     *
     * @param contract          ContractDto
     * @param positionOpenDate  ZonedDateTime
     * @param positionCloseDate ZonedDateTime
     * @param openQuantity      Integer
     * @param side              String
     * @param totalBuyQuantity  Integer
     * @param totalBuyValue     BigDecimal
     * @param totalSellQuantity Integer
     * @param totalSellValue    BigDecimal
     * @param totalNetValue     BigDecimal
     * @param tradeOrders       List<TradeOrder>
     */
    public TradePositionDTO(ContractDTO contract, ZonedDateTime positionOpenDate, ZonedDateTime positionCloseDate,
                            Integer openQuantity, String side, BigDecimal totalCommission, Integer totalBuyQuantity,
                            BigDecimal totalBuyValue, Integer totalSellQuantity, BigDecimal totalSellValue, BigDecimal totalNetValue,
                            List<TradeOrderDTO> tradeOrders) {

        this.contract = contract;
        this.openDate = positionOpenDate;
        this.closeDate = positionCloseDate;
        this.openQuantity = openQuantity;
        this.side = side;
        this.totalCommission = totalCommission;
        this.totalBuyQuantity = totalBuyQuantity;
        this.totalBuyValue = totalBuyValue;
        this.totalSellQuantity = totalSellQuantity;
        this.totalSellValue = totalSellValue;
        this.totalNetValue = totalNetValue;
        this.tradeOrderDTOs = tradeOrders;
    }

    /**
     * Method getContract.
     *
     * @return ContractDto
     */
    public ContractDTO getContract() {
        return this.contract;
    }

    /**
     * Method setContract.
     *
     * @param contract ContractDto
     */
    public void setContract(ContractDTO contract) {
        this.contract = contract;
    }

    /**
     * Method getPositionOpenDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getOpenDate() {
        return this.openDate;
    }

    /**
     * Method setPositionOpenDate.
     *
     * @param openDate ZonedDateTime
     */
    public void setOpenDate(ZonedDateTime openDate) {
        this.openDate = openDate;
    }

    /**
     * Method getPositionCloseDate.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getCloseDate() {
        return this.closeDate;
    }

    /**
     * Method setPositionCloseDate.
     *
     * @param closeDate ZonedDateTime
     */
    public void setCloseDate(ZonedDateTime closeDate) {
        this.closeDate = closeDate;
    }

    /**
     * Method getOpenQuantity.
     *
     * @return Integer
     */
    public Integer getOpenQuantity() {
        return this.openQuantity;
    }

    /**
     * Method setOpenQuantity.
     *
     * @param openQuantity Integer
     */
    public void setOpenQuantity(Integer openQuantity) {
        this.openQuantity = openQuantity;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }

    /**
     * Method setSide.
     *
     * @param side String
     */
    public void setSide(String side) {
        this.side = side;
    }

    /**
     * Method getTotalCommission.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalCommission() {
        return this.totalCommission;
    }

    /**
     * Method setTotalCommission.
     *
     * @param totalCommission BigDecimal
     */
    public void setTotalCommission(BigDecimal totalCommission) {
        this.totalCommission = totalCommission;
    }

    /**
     * Method getTotalBuyQuantity.
     *
     * @return Integer
     */
    public Integer getTotalBuyQuantity() {
        return this.totalBuyQuantity;
    }

    /**
     * Method setTotalBuyQuantity.
     *
     * @param totalBuyQuantity Integer
     */
    public void setTotalBuyQuantity(Integer totalBuyQuantity) {
        this.totalBuyQuantity = totalBuyQuantity;
    }

    /**
     * Method getTotalSellQuantity.
     *
     * @return Integer
     */
    public Integer getTotalSellQuantity() {
        return this.totalSellQuantity;
    }

    /**
     * Method setTotalSellQuantity.
     *
     * @param totalSellQuantity Integer
     */
    public void setTotalSellQuantity(Integer totalSellQuantity) {
        this.totalSellQuantity = totalSellQuantity;
    }

    /**
     * Method getTotalBuyValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalBuyValue() {
        return this.totalBuyValue;
    }

    /**
     * Method setTotalBuyValue.
     *
     * @param totalBuyValue BigDecimal
     */
    public void setTotalBuyValue(BigDecimal totalBuyValue) {
        this.totalBuyValue = totalBuyValue;
    }

    /**
     * Method getTotalSellValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalSellValue() {
        return this.totalSellValue;
    }

    /**
     * Method setTotalSellValue.
     *
     * @param totalSellValue BigDecimal
     */
    public void setTotalSellValue(BigDecimal totalSellValue) {
        this.totalSellValue = totalSellValue;
    }

    /**
     * Method getTotalNetValue.
     *
     * @return BigDecimal
     */
    public BigDecimal getTotalNetValue() {
        return this.totalNetValue;
    }

    /**
     * Method setTotalNetValue.
     *
     * @param totalNetValue BigDecimal
     */
    public void setTotalNetValue(BigDecimal totalNetValue) {
        this.totalNetValue = totalNetValue;
    }

    /**
     * Method getTradeOrders.
     *
     * @return List<TradeOrderDto>
     */
    public List<TradeOrderDTO> getTradeOrderDTOs() {
        return this.tradeOrderDTOs;
    }

    /**
     * Method setTradeOrders.
     *
     * @param tradeOrderDTOs List<TradeOrderDto>
     */
    @JsonIgnore
    public void setTradeOrderDTOs(List<TradeOrderDTO> tradeOrderDTOs) {
        this.tradeOrderDTOs = tradeOrderDTOs;
    }

    /**
     * Method addTradeOrder.
     *
     * @param tradeOrders TradeOrderDto
     */
    public void addTradeOrder(TradeOrderDTO tradeOrders) {
        this.tradeOrderDTOs.add(tradeOrders);
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {

        return "TradePosition Id: " + this.getId() + " Version: " + this.getVersion()
                + " positionOpenDate: " + this.getOpenDate() + " positionCloseDate: "
                + this.getCloseDate() + " Side: " + this.getSide() + " Open Qty: " + this.getOpenQuantity()
                + " Total Buy qty: " + this.getTotalBuyQuantity() + " Total Buy Value: "
                + new Money(this.getTotalBuyValue()) + " Total Sell qty: " + this.getTotalSellQuantity()
                + " Total Sell Value: " + new Money(this.getTotalSellValue()) + " Total Comm: "
                + new Money(this.getTotalCommission()) + " updatedDate: " + this.getUpdatedDate();
    }
}
