package org.trade.core.persistent.dao;

import org.trade.core.dao.Aspect;

import java.io.Serial;
import java.io.Serializable;


/**
 * TradestrategyContract generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class TradestrategyLiteDTO extends Aspect implements Serializable {

    @Serial
    private static final long serialVersionUID = -2181676329258092177L;

    private String status;

    public TradestrategyLiteDTO() {
    }

    /**
     * Constructor for TradestrategyLite. Need for filtered query that just
     * gets the current version
     *
     * @param id      Integer
     * @param version Integer
     */
    public TradestrategyLiteDTO(Long id, Integer version) {

        setId(id);
        this.version = version;
    }

    /**
     * Method getStatus.
     *
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Method setStatus.
     *
     * @param status String
     */
    public void setStatus(String status) {
        this.status = status;
    }
}
