package org.trade.core.persistent.dao;

// Generated Feb 21, 2011 12:43:33 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.trade.core.dao.Aspect;
import org.trade.core.valuetype.Money;

import java.io.Serial;
import java.math.BigDecimal;
import java.time.ZonedDateTime;


/**
 * Orderfill generated by hbm2java
 *
 * @author Simon Allen
 * @version $Revision: 1.0 $
 */
public class TradeOrderfillDTO extends Aspect implements java.io.Serializable, Cloneable {

    @Serial
    private static final long serialVersionUID = -4345234694835258864L;

    private String accountNumber;
    private Integer quantity;
    private String side;
    private String exchange;
    private BigDecimal price;
    private ZonedDateTime time;
    private BigDecimal averagePrice;
    private Integer cumulativeQuantity;
    private String execId;
    private BigDecimal commission;
    private String orderReference;
    private Integer permId;
    private TradeOrderDTO tradeOrder;

    public TradeOrderfillDTO() {
    }

    /**
     * Constructor for TradeOrderfill.
     *
     * @param tradeOrder         TradeOrderDto
     * @param accountNumber      String
     * @param averagePrice       BigDecimal
     * @param cumulativeQuantity Integer
     * @param exchange           String
     * @param execId             String
     * @param price              BigDecimal
     * @param quantity           Integer
     * @param side               String
     * @param time               Date
     */
    public TradeOrderfillDTO(TradeOrderDTO tradeOrder, String accountNumber, BigDecimal averagePrice,
                             Integer cumulativeQuantity, String exchange, String execId, BigDecimal price, Integer quantity, String side,
                             ZonedDateTime time) {

        this.tradeOrder = tradeOrder;
        this.accountNumber = accountNumber;
        this.averagePrice = averagePrice;
        this.cumulativeQuantity = cumulativeQuantity;
        this.execId = execId;
        this.exchange = exchange;
        this.price = price;
        this.quantity = quantity;
        this.side = side;
        this.time = time;
    }

    /**
     * Method getTradeOrder.
     *
     * @return TradeOrderDto
     */
    public TradeOrderDTO getTradeOrder() {
        return this.tradeOrder;
    }

    /**
     * Method setTradeOrder.
     *
     * @param tradeOrder TradeOrderDto
     */
    @JsonIgnore
    public void setTradeOrder(TradeOrderDTO tradeOrder) {
        this.tradeOrder = tradeOrder;
    }

    /**
     * Method getAccountNumber.
     *
     * @return String
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Method setAccountNumber.
     *
     * @param accountNumber String
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Method getAveragePrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getAveragePrice() {
        return this.averagePrice;
    }

    /**
     * Method setAveragePrice.
     *
     * @param averagePrice BigDecimal
     */
    public void setAveragePrice(BigDecimal averagePrice) {
        this.averagePrice = averagePrice;
    }

    /**
     * Method getCommission.
     *
     * @return BigDecimal
     */
    public BigDecimal getCommission() {
        return this.commission;
    }

    /**
     * Method setCommission.
     *
     * @param commission BigDecimal
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * Method getCumulativeQuantity.
     *
     * @return Integer
     */
    public Integer getCumulativeQuantity() {
        return this.cumulativeQuantity;
    }

    /**
     * Method setCumulativeQuantity.
     *
     * @param cumulativeQuantity Integer
     */
    public void setCumulativeQuantity(Integer cumulativeQuantity) {
        this.cumulativeQuantity = cumulativeQuantity;
    }

    /**
     * Method getExecId.
     *
     * @return String
     */
    public String getExecId() {
        return this.execId;
    }

    /**
     * Method setExecId.
     *
     * @param execId String
     */
    public void setExecId(String execId) {
        this.execId = execId;
    }

    /**
     * Method getOrderReference.
     *
     * @return String
     */
    public String getOrderReference() {
        return this.orderReference;
    }

    /**
     * Method setOrderReference.
     *
     * @param orderReference String
     */
    public void setOrderReference(String orderReference) {
        this.orderReference = orderReference;
    }

    /**
     * Method getExchange.
     *
     * @return String
     */
    public String getExchange() {
        return this.exchange;
    }

    /**
     * Method setExchange.
     *
     * @param exchange String
     */
    public void setExchange(String exchange) {
        this.exchange = exchange;
    }

    /**
     * Method getPermId.
     *
     * @return Integer
     */
    public Integer getPermId() {
        return this.permId;
    }

    /**
     * Method setPermId.
     *
     * @param permId Integer
     */
    public void setPermId(Integer permId) {
        this.permId = permId;
    }

    /**
     * Method getPrice.
     *
     * @return BigDecimal
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Method setPrice.
     *
     * @param price BigDecimal
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Method getQuantity.
     *
     * @return Integer
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Method setQuantity.
     *
     * @param quantity Integer
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Method getSide.
     *
     * @return String
     */
    public String getSide() {
        return this.side;
    }

    /**
     * Method setSide.
     *
     * @param side String
     */
    public void setSide(String side) {
        this.side = side;
    }

    /**
     * Method getTime.
     *
     * @return ZonedDateTime
     */
    public ZonedDateTime getTime() {
        return this.time;
    }

    /**
     * Method setTime.
     *
     * @param time ZonedDateTime
     */
    public void setTime(ZonedDateTime time) {
        this.time = time;
    }

    /**
     * Method clone.
     *
     * @return TradeOrderfill
     */
    public TradeOrderfillDTO clone() {

        try {

            return (TradeOrderfillDTO) super.clone();
        } catch (CloneNotSupportedException e) {
            // will never happen
            return null;
        }
    }

    /**
     * Method toString.
     *
     * @return String
     */
    public String toString() {

        return "Order Id: " + this.getTradeOrder().getId() + " OrderKey: "
                + this.getTradeOrder().getOrderKey() + " Trade Order Version: " + this.getTradeOrder().getVersion()
                + " Order Fill Id: " + this.getId() + " Order Fill Version: " + this.getVersion()
                + " Quantity: " + this.getQuantity() + " Avg Price: " + new Money(this.getAveragePrice()) + " Cum Qty: "
                + this.getCumulativeQuantity() + " Price: " + new Money(this.getPrice()) + " Exchange: "
                + this.getExchange() + " Side: " + this.getSide() + " Time: " + this.getTime();
    }
}
